// Product-page copy added after the original translation pass. Keeping each
// phrase as one explicit three-language record makes additions reviewable.
export const launchCopy = {
  '。': { zh: '。', en: '.', ar: '.' },
  'WECOM SALES ANALYSIS': { zh: 'WECOM SALES ANALYSIS', en: 'WECOM SALES ANALYSIS', ar: 'تحليل مبيعات WECOM' },
  '企微销售分析，<br />让客户对话变成 <em>可行动的洞察</em>。': { zh: '企微销售分析，<br />让客户对话变成 <em>可行动的洞察</em>。', en: 'WeCom sales analysis turns customer conversations into <em>actionable insight</em>.', ar: 'يحوّل تحليل مبيعات WeCom محادثات العملاء إلى <em>رؤى قابلة للتنفيذ</em>.' },
  '让客户对话变成': { zh: '让客户对话变成', en: 'turn customer conversations into', ar: 'حوّل محادثات العملاء إلى' },
  '可行动的洞察': { zh: '可行动的洞察', en: 'actionable insight', ar: 'رؤى قابلة للتنفيذ' },
  '汇总企微里的真实沟通，识别客户意向、销售表现和待跟进事项，帮助团队更及时地复盘与行动。': { zh: '汇总企微里的真实沟通，识别客户意向、销售表现和待跟进事项，帮助团队更及时地复盘与行动。', en: 'Bring real WeCom conversations together to identify customer intent, sales performance, and follow-up items so teams can review and act sooner.', ar: 'اجمع محادثات WeCom الفعلية لاكتشاف نوايا العملاء وأداء المبيعات وبنود المتابعة، كي يتمكن الفريق من المراجعة والتحرك بسرعة.' },
  '打开企微销售分析体验页面': { zh: '打开企微销售分析体验页面', en: 'Open the WeCom sales analysis demo', ar: 'افتح تجربة تحليل مبيعات WeCom' },
  '企微销售分析界面': { zh: '企微销售分析界面', en: 'WeCom sales analysis interface', ar: 'واجهة تحليل مبيعات WeCom' },
  '体验企微销售分析 ↗': { zh: '体验企微销售分析 ↗', en: 'Try WeCom sales analysis ↗', ar: 'جرّب تحليل مبيعات WeCom ↗' },
  'Tellyn｜高价值销售团队的 AI Copilot': { zh: 'Tellyn｜高价值销售团队的 AI Copilot', en: 'Tellyn | AI Copilot for high-value sales teams', ar: 'Tellyn | مساعد ذكاء اصطناعي لفرق المبيعات عالية القيمة' },
  '医疗与医疗器械': { zh: '医疗与医疗器械', en: 'Healthcare & medical devices', ar: 'الرعاية الصحية والأجهزة الطبية' },
  '一次专业沟通，不能只留在销售的记忆里。': { zh: '一次专业沟通，不能只留在销售的记忆里。', en: 'A professional conversation should not live only in a salesperson’s memory.', ar: 'لا ينبغي أن تبقى المحادثة المهنية في ذاكرة مندوب المبيعات وحده.' },
  '医生、科室与采购关心的问题不同，产品信息专业，决策链长，复盘往往依赖销售手写笔记。': { zh: '医生、科室与采购关心的问题不同，产品信息专业，决策链长，复盘往往依赖销售手写笔记。', en: 'Doctors, departments, and procurement teams care about different things. Product information is specialized, decisions take time, and reviews often rely on handwritten sales notes.', ar: 'يهتم الأطباء والأقسام وفرق المشتريات بأمور مختلفة. معلومات المنتج متخصصة، ودورة القرار طويلة، وغالباً ما تعتمد المراجعة على ملاحظات المبيعات المكتوبة.' },
  '还原产品问题与临床关注点': { zh: '还原产品问题与临床关注点', en: 'Capture product questions and clinical concerns', ar: 'توثيق أسئلة المنتج والاعتبارات السريرية' },
  '区分使用顾虑、采购条件与关键人': { zh: '区分使用顾虑、采购条件与关键人', en: 'Separate usage concerns, purchasing terms, and key stakeholders', ar: 'تمييز مخاوف الاستخدام وشروط الشراء وأصحاب القرار' },
  '生成准确的会后摘要与内部协同事项': { zh: '生成准确的会后摘要与内部协同事项', en: 'Create accurate meeting summaries and internal action items', ar: 'إنشاء ملخصات دقيقة للاجتماعات ومهام تنسيق داخلية' },
  '汽车销售': { zh: '汽车销售', en: 'Automotive sales', ar: 'مبيعات السيارات' },
  '试驾结束后，真正的销售工作才刚开始。': { zh: '试驾结束后，真正的销售工作才刚开始。', en: 'The real sales work begins after the test drive.', ar: 'يبدأ عمل المبيعات الحقيقي بعد انتهاء تجربة القيادة.' },
  '预算、车型偏好、旧车置换、家庭意见和竞品比较散落在一段长对话里，跟进很容易只剩一句“再考虑”。': { zh: '预算、车型偏好、旧车置换、家庭意见和竞品比较散落在一段长对话里，跟进很容易只剩一句“再考虑”。', en: 'Budget, model preferences, trade-ins, family opinions, and competitor comparisons are scattered through a long conversation, leaving follow-up reduced to “still considering.”', ar: 'تتوزع الميزانية وتفضيلات الطراز والاستبدال ورأي الأسرة ومقارنات المنافسين عبر محادثة طويلة، وقد تختصر المتابعة بسهولة إلى «ما زال يفكر».' },
  '提取车型偏好、预算与购买时点': { zh: '提取车型偏好、预算与购买时点', en: 'Extract model preferences, budget, and purchase timing', ar: 'استخراج تفضيلات الطراز والميزانية وموعد الشراء' },
  '识别价格、配置与竞品异议': { zh: '识别价格、配置与竞品异议', en: 'Identify pricing, configuration, and competitor objections', ar: 'تحديد الاعتراضات المتعلقة بالسعر والمواصفات والمنافسين' },
  '给销售清晰的下一次触达建议': { zh: '给销售清晰的下一次触达建议', en: 'Give sales a clear recommendation for the next touchpoint', ar: 'منح فريق المبيعات توصية واضحة للتواصل التالي' },
  '房产销售': { zh: '房产销售', en: 'Real estate sales', ar: 'مبيعات العقارات' },
  '每次带看，都应该让下一套推荐更准确。': { zh: '每次带看，都应该让下一套推荐更准确。', en: 'Every viewing should make the next recommendation more accurate.', ar: 'يجب أن تجعل كل معاينة التوصية التالية أكثر دقة.' },
  '客户会在通勤、学区、户型、楼层、付款安排之间反复权衡，多次带看的信息难以被团队完整接续。': { zh: '客户会在通勤、学区、户型、楼层、付款安排之间反复权衡，多次带看的信息难以被团队完整接续。', en: 'Clients weigh commute, schools, layout, floor, and payment options repeatedly. Information across multiple viewings is hard for teams to carry forward.', ar: 'يوازن العملاء مراراً بين التنقل والمدارس والتخطيط والطابق وخيارات الدفع، ويصعب على الفريق متابعة معلومات المعاينات المتعددة بالكامل.' },
  '沉淀显性需求与未说出口的顾虑': { zh: '沉淀显性需求与未说出口的顾虑', en: 'Capture stated needs and unspoken concerns', ar: 'توثيق الاحتياجات المعلنة والمخاوف غير المصرح بها' },
  '整理决策人、时间线和资金安排': { zh: '整理决策人、时间线和资金安排', en: 'Organize decision-makers, timelines, and financing plans', ar: 'تنظيم أصحاب القرار والجداول الزمنية وخطط التمويل' },
  '帮助经纪人准备更贴合的房源与话术': { zh: '帮助经纪人准备更贴合的房源与话术', en: 'Help agents prepare better-matched listings and conversations', ar: 'مساعدة الوسطاء على إعداد عقارات ورسائل أكثر ملاءمة' },
  '收好每一次对话': { zh: '收好每一次对话', en: 'Capture every conversation', ar: 'احفظ كل محادثة' },
  '在获得客户同意的前提下记录沟通，让关键信息不再散落在录音、聊天和个人笔记中。': { zh: '在获得客户同意的前提下记录沟通，让关键信息不再散落在录音、聊天和个人笔记中。', en: 'Record conversations with customer consent, so key information is no longer scattered across recordings, chats, and personal notes.', ar: 'سجّل المحادثات بموافقة العميل، حتى لا تبقى المعلومات المهمة موزعة بين التسجيلات والمحادثات والملاحظات الشخصية.' },
  '理解客户真正关心什么': { zh: '理解客户真正关心什么', en: 'Understand what customers truly care about', ar: 'افهم ما يهم العميل فعلاً' },
  '自动整理需求、问题、异议、购买信号和待确认事项，还原完整决策语境。': { zh: '自动整理需求、问题、异议、购买信号和待确认事项，还原完整决策语境。', en: 'Automatically organize needs, questions, objections, buying signals, and open items to preserve the full decision context.', ar: 'نظّم تلقائياً الاحتياجات والأسئلة والاعتراضات وإشارات الشراء والنقاط المعلقة للحفاظ على سياق القرار كاملاً.' },
  '把洞察变成下一步动作': { zh: '把洞察变成下一步动作', en: 'Turn insight into the next action', ar: 'حوّل الرؤى إلى الخطوة التالية' },
  '生成跟进摘要、建议与协同任务，让销售知道接下来该联系谁、说什么、准备什么。': { zh: '生成跟进摘要、建议与协同任务，让销售知道接下来该联系谁、说什么、准备什么。', en: 'Generate follow-up summaries, recommendations, and team tasks so sales knows who to contact, what to say, and what to prepare.', ar: 'أنشئ ملخصات وتوصيات ومهام متابعة ليعرف فريق المبيعات بمن يتصل وماذا يقول وماذا يجهز.' },
  '让一线经验成为团队资产': { zh: '让一线经验成为团队资产', en: 'Make frontline experience a team asset', ar: 'حوّل خبرة الميدان إلى أصل للفريق' },
  '把高质量问法、常见异议与有效跟进持续沉淀，帮助新人更快进入状态。': { zh: '把高质量问法、常见异议与有效跟进持续沉淀，帮助新人更快进入状态。', en: 'Continuously retain strong questions, common objections, and effective follow-ups so new hires ramp faster.', ar: 'راكم الأسئلة الجيدة والاعتراضات الشائعة وأساليب المتابعة الفعالة لمساعدة المنضمين الجدد على الانطلاق أسرع.' },
  '销售团队围绕客户洞察协作的手绘插图': { zh: '销售团队围绕客户洞察协作的手绘插图', en: 'Hand-drawn illustration of a sales team collaborating around customer insights', ar: 'رسم توضيحي يدوي لفريق مبيعات يتعاون حول رؤى العملاء' },
  '汽车销售向客户介绍车辆的手绘插图': { zh: '汽车销售向客户介绍车辆的手绘插图', en: 'Hand-drawn illustration of a car salesperson presenting a vehicle to customers', ar: 'رسم توضيحي يدوي لمندوب مبيعات سيارات يعرض مركبة على العملاء' },
  'Tellyn 销售洞察与经营总览界面': { zh: 'Tellyn 销售洞察与经营总览界面', en: 'Tellyn sales insights and business overview interface', ar: 'واجهة Tellyn لرؤى المبيعات ونظرة الأعمال العامة' },
  'Tellyn 产品页': { zh: 'Tellyn 产品页', en: 'Tellyn product page', ar: 'صفحة منتج Tellyn' },
  '让每一次销售对话，': { zh: '让每一次销售对话，', en: 'Make every sales conversation', ar: 'اجعل كل محادثة مبيعات' },
  '都推动客户走向': { zh: '都推动客户走向', en: 'move the customer toward ', ar: 'تدفع العميل نحو ' },
  '下一步': { zh: '下一步', en: 'the next step', ar: 'الخطوة التالية' },
  '面向医疗、汽车、房产等高客单价、长决策链的销售团队。Tellyn 记录客户怎么说，理解他们真正关心什么，并把关键洞察变成可执行的跟进建议。': { zh: '面向医疗、汽车、房产等高客单价、长决策链的销售团队。Tellyn 记录客户怎么说，理解他们真正关心什么，并把关键洞察变成可执行的跟进建议。', en: 'Built for healthcare, automotive, real estate, and other high-value sales teams with long decision cycles. Tellyn captures what customers say, understands what matters, and turns key insights into actionable follow-up.', ar: 'مصمم لفرق المبيعات عالية القيمة وذات دورات القرار الطويلة في الرعاية الصحية والسيارات والعقارات وغيرها. يسجل Tellyn ما يقوله العملاء ويفهم ما يهمهم ويحول الرؤى إلى متابعة قابلة للتنفيذ.' },
  '预约产品演示': { zh: '预约产品演示', en: 'Book a product demo', ar: 'احجز عرضاً للمنتج' },
  '看看适合哪些场景': { zh: '看看适合哪些场景', en: 'Explore use cases', ar: 'استكشف حالات الاستخدام' },
  '客户对话': { zh: '客户对话', en: 'Customer conversations', ar: 'محادثات العملاء' },
  '需求与异议': { zh: '需求与异议', en: 'Needs & objections', ar: 'الاحتياجات والاعتراضات' },
  '跟进动作': { zh: '跟进动作', en: 'Follow-up actions', ar: 'إجراءات المتابعة' },
  '团队知识': { zh: '团队知识', en: 'Team knowledge', ar: 'معرفة الفريق' },
  'AI 整理完成': { zh: 'AI 整理完成', en: 'AI analysis complete', ar: 'اكتمل تحليل الذكاء الاصطناعي' },
  '3 个购买信号': { zh: '3 个购买信号', en: '3 buying signals', ar: '3 إشارات شراء' },
  '2 项待跟进事项': { zh: '2 项待跟进事项', en: '2 follow-up items', ar: 'مهمتان للمتابعة' },
  '销售团队真正缺的，往往不是更多客户数据。': { zh: '销售团队真正缺的，往往不是更多客户数据。', en: 'What sales teams lack is rarely more customer data.', ar: 'ما تفتقده فرق المبيعات غالباً ليس المزيد من بيانات العملاء.' },
  '而是把散落在对话里的需求、异议和承诺，': { zh: '而是把散落在对话里的需求、异议和承诺，', en: 'It is turning needs, objections, and commitments scattered through conversations', ar: 'بل تحويل الاحتياجات والاعتراضات والالتزامات المتناثرة في المحادثات' },
  '变成每个人都能接住的': { zh: '变成每个人都能接住的', en: 'into context everyone can act on ', ar: 'إلى سياق يستطيع الجميع العمل عليه' },
  '越复杂的成交，': { zh: '越复杂的成交，', en: 'The more complex the sale,', ar: 'كلما ازدادت الصفقة تعقيداً،' },
  '越需要把客户': { zh: '越需要把客户', en: 'the more clearly you need to ', ar: 'ازدادت الحاجة إلى' },
  '听明白': { zh: '听明白', en: 'understand the customer', ar: 'فهم العميل بوضوح' },
  '同样是“客户再考虑”，背后可能是专业风险、家庭意见、预算安排或竞品比较。Tellyn 帮销售团队保留语境，而不只是记下几个关键词。': { zh: '同样是“客户再考虑”，背后可能是专业风险、家庭意见、预算安排或竞品比较。Tellyn 帮销售团队保留语境，而不只是记下几个关键词。', en: '“Still considering” may mean professional risk, family opinion, budget planning, or competitor comparison. Tellyn helps sales teams retain the context, not just a few keywords.', ar: 'قد تعني عبارة «ما زال يفكر» مخاطر مهنية أو رأي الأسرة أو ترتيب الميزانية أو مقارنة المنافسين. يساعد Tellyn الفريق على الاحتفاظ بالسياق لا ببضع كلمات مفتاحية فقط.' },
  '不是一份冷冰冰的转写，': { zh: '不是一份冷冰冰的转写，', en: 'Not a cold transcript,', ar: 'ليست مجرد نسخة نصية جامدة،' },
  '而是一套': { zh: '而是一套', en: 'but a complete ', ar: 'بل منظومة' },
  '跟进闭环': { zh: '跟进闭环', en: 'follow-up loop', ar: 'متابعة متكاملة' },
  '管理者看见共性，': { zh: '管理者看见共性，', en: 'Managers see the patterns,', ar: 'يرى المديرون الأنماط المشتركة،' },
  '一线得到': { zh: '一线得到', en: 'frontline teams get ', ar: 'وتحصل الفرق الميدانية على' },
  '具体帮助': { zh: '具体帮助', en: 'practical help', ar: 'مساعدة عملية' },
  '单次对话服务于跟进，跨门店与跨团队的对话则帮助管理者发现反复出现的客户问题、产品反馈与流程阻塞。': { zh: '单次对话服务于跟进，跨门店与跨团队的对话则帮助管理者发现反复出现的客户问题、产品反馈与流程阻塞。', en: 'Each conversation supports follow-up. Conversations across stores and teams help managers identify recurring customer questions, product feedback, and process bottlenecks.', ar: 'تدعم كل محادثة المتابعة، بينما تساعد المحادثات عبر الفروع والفرق المديرين على اكتشاف أسئلة العملاء المتكررة وملاحظات المنتج وعوائق العمليات.' },
  '对销售': { zh: '对销售', en: 'For sales', ar: 'لفريق المبيعات' },
  '更少整理时间，更清楚的客户上下文和下一步。': { zh: '更少整理时间，更清楚的客户上下文和下一步。', en: 'Less admin time, clearer customer context, and a clearer next step.', ar: 'وقت أقل للتنظيم وسياق أوضح للعميل وخطوة تالية محددة.' },
  '对主管': { zh: '对主管', en: 'For managers', ar: 'للمديرين' },
  '看见团队共性问题，辅导不再只凭结果猜原因。': { zh: '看见团队共性问题，辅导不再只凭结果猜原因。', en: 'See shared team issues and coach from evidence instead of guessing from outcomes.', ar: 'رؤية مشكلات الفريق المشتركة والتوجيه بناءً على الأدلة بدلاً من تخمين الأسباب من النتائج.' },
  '对业务': { zh: '对业务', en: 'For the business', ar: 'للأعمال' },
  '让客户之声持续进入产品、市场与经营决策。': { zh: '让客户之声持续进入产品、市场与经营决策。', en: 'Continuously bring the voice of the customer into product, marketing, and operating decisions.', ar: 'إدخال صوت العميل باستمرار في قرارات المنتج والتسويق والتشغيل.' },
  '先从一支团队、': { zh: '先从一支团队、', en: 'Start with one team', ar: 'ابدأ بفريق واحد' },
  '一种对话开始。': { zh: '一种对话开始。', en: 'and one type of conversation.', ar: 'ونوع واحد من المحادثات.' },
  '我们会先了解你的销售流程、客户决策链和已有工具，再一起选择最值得验证的沟通场景。是否适合、怎么接入、哪些信息需要保护，都会在演示与诊断中说清楚。': { zh: '我们会先了解你的销售流程、客户决策链和已有工具，再一起选择最值得验证的沟通场景。是否适合、怎么接入、哪些信息需要保护，都会在演示与诊断中说清楚。', en: 'We first understand your sales process, customer decision journey, and existing tools, then choose the conversation worth validating. Fit, integration, and data protection are clarified during the demo and diagnosis.', ar: 'نفهم أولاً عملية المبيعات ومسار قرار العميل والأدوات الحالية، ثم نختار معاً المحادثة الأجدر بالاختبار. سنوضح الملاءمة والتكامل وحماية المعلومات خلال العرض والتشخيص.' },
  '带一个真实销售场景来聊': { zh: '带一个真实销售场景来聊', en: 'Bring a real sales scenario', ar: 'ناقشنا في سيناريو مبيعات حقيقي' },
}
