const entry = (zh, en, ar) => [zh, { zh, en, ar }]

export const qixiaoCopy = Object.fromEntries([
  entry('启晓', 'Qixiao', 'Qixiao'),
  entry('启晓｜AI 公关舆情工作系统', 'Qixiao | AI PR intelligence work system', 'Qixiao | نظام عمل ذكي للعلاقات العامة'),
  entry('启晓产品页', 'Qixiao product page', 'صفحة منتج Qixiao'),
  entry('启晓 AI 公关工作系统总览', 'Qixiao AI PR work system overview', 'نظرة عامة على نظام Qixiao للعلاقات العامة'),
  entry('启晓舆情监测与智能管控中心', 'Qixiao monitoring and intelligent control center', 'مركز Qixiao للرصد والتحكم الذكي'),
  entry('启晓舆情专家 Agent 工作流程', 'Qixiao PR agent workflow', 'سير عمل وكيل Qixiao للعلاقات العامة'),
  entry('启晓舆情分析报告示例', 'Qixiao PR intelligence report example', 'نموذج تقرير تحليل Qixiao'),
  entry('，把全网舆情', ' turns public conversation', ' يحوّل النقاش العام'),
  entry('变成可执行的', 'into actionable ', 'إلى '),
  entry('公关判断', 'PR judgment', 'قرار علاقات عامة قابل للتنفيذ'),
  entry('启晓以企业专属模型、知识库与智能体重构舆情工作流，从全网发现、事件研判到行动建议和复盘沉淀，帮助公关团队更早看见真正的风险。', 'Qixiao uses company-specific models, knowledge, and agents to connect discovery, event assessment, action guidance, and review—helping PR teams see real risk sooner.', 'يستخدم Qixiao نماذج ومعرفة ووكلاء مخصصين للمؤسسة لربط الاكتشاف وتقييم الأحداث واقتراح الإجراءات والمراجعة، مما يساعد فرق العلاقات العامة على رؤية المخاطر الحقيقية مبكراً.'),
  entry('持续学习', 'Continuous learning', 'تعلم مستمر'),
  entry('了解启晓', 'Explore Qixiao', 'اكتشف Qixiao'),
  entry('不只看见舆情，', 'Go beyond monitoring.', 'تجاوز مجرد الرصد.'),
  entry('更早形成', 'Form ', 'اتخذ '),
  entry('可执行的判断', 'actionable judgment sooner', 'قرارات قابلة للتنفيذ مبكراً'),
  entry('启晓是面向企业与品牌定制的 AI 公关工作系统。它以专属模型、企业知识库和 Agent 工作流，连接发现、研判、响应与复盘，让公关团队从信息汇总走向决策协同。', 'Qixiao is a configurable AI PR work system for enterprises and brands. Dedicated models, company knowledge, and agent workflows connect discovery, assessment, response, and review so PR teams can move from information collection to coordinated decisions.', 'Qixiao نظام عمل ذكي قابل للتخصيص للمؤسسات والعلامات التجارية. يربط بين الاكتشاف والتقييم والاستجابة والمراجعة عبر نماذج مخصصة ومعرفة المؤسسة ووكلاء ذكيين، لينقل الفريق من جمع المعلومات إلى تنسيق القرار.'),
  entry('了解工作闭环', 'See the decision loop', 'اكتشف دورة العمل'),
  entry('发现', 'Discover', 'اكتشاف'), entry('理解', 'Understand', 'فهم'), entry('研判', 'Assess', 'تقييم'), entry('行动', 'Act', 'إجراء'), entry('复盘', 'Review', 'مراجعة'),
  entry('传统舆情工具的问题，不在于能不能监测，而在于能不能快速理解、判断和迭代。', 'The limit of traditional monitoring is not collection—it is how quickly teams can understand, judge, and adapt.', 'محدودية أدوات الرصد التقليدية ليست في الجمع، بل في سرعة الفهم والحكم والتكيف.'),
  entry('当风险进入语境、圈层与传播链路，', 'When risk moves through context, communities, and propagation paths,', 'عندما تنتقل المخاطر عبر السياق والمجتمعات ومسارات الانتشار،'),
  entry('只看关键词和声量，已经', 'keywords and volume are ', 'لا تعود الكلمات المفتاحية والحجم '), entry('不够了', 'not enough', 'كافيين'),
  entry('关键词命中，不等于真实风险', 'A keyword match is not real risk', 'تطابق الكلمة ليس خطراً حقيقياً'),
  entry('玩梗、反讽、二创与搬运会制造大量噪声。企业需要理解讨论对象、语气、意图和语境，而不只是看词有没有出现。', 'Memes, irony, remixes, and reposts create noise. Brands need to understand the subject, tone, intent, and context—not merely whether a term appears.', 'تخلق النكات والسخرية وإعادة الإنتاج والنشر ضوضاء كبيرة. تحتاج العلامة إلى فهم الموضوع والنبرة والنية والسياق، لا مجرد ظهور كلمة.'),
  entry('声量高低，不等于舆情伤害', 'Volume does not equal reputational harm', 'حجم النقاش لا يساوي الضرر السمعة'),
  entry('一条高传播切片可能比大量低互动链接更值得优先处理，需要结合账号权重、传播速度与跨平台扩散判断影响。', 'One highly shared clip may matter more than many low-engagement links. Priority should reflect account influence, velocity, and cross-platform spread.', 'قد يكون مقطع واسع الانتشار أهم من روابط كثيرة ضعيفة التفاعل. يجب تقدير الأولوية وفق تأثير الحساب وسرعة الانتشار وانتقاله بين المنصات.'),
  entry('静态报告，赶不上风险变化', 'Static reports cannot keep pace with risk', 'التقارير الثابتة لا تواكب المخاطر'),
  entry('新梗、新账号和新议题不断出现，固定规则与项目制排期很难持续跟上公关团队的判断节奏。', 'New memes, accounts, and issues emerge continuously. Fixed rules and project schedules struggle to match a PR team’s decision cycle.', 'تظهر باستمرار عبارات وحسابات وقضايا جديدة، ولا تستطيع القواعد الثابتة وجداول المشاريع مجاراة إيقاع قرارات فريق العلاقات العامة.'),
  entry('从“看见信息”，', 'From seeing information', 'من رؤية المعلومات'), entry('走到', 'to ', 'إلى '), entry('处理与复盘', 'action and review', 'المعالجة والمراجعة'),
  entry('AI 负责发现、聚合、研判与报告起草，团队聚焦事实确认、策略选择与最终对外口径。高风险结论始终保留原文证据、判断依据和人工复核。', 'AI handles discovery, aggregation, assessment, and report drafting. Teams focus on fact-checking, strategy, and final statements. High-risk conclusions retain source evidence, rationale, and human review.', 'يتولى الذكاء الاصطناعي الاكتشاف والتجميع والتقييم وصياغة التقارير، بينما يركز الفريق على التحقق والاستراتيجية والصياغة النهائية. تحتفظ النتائج عالية المخاطر بالأدلة والمنطق والمراجعة البشرية.'),
  entry('全网发现', 'Open-web discovery', 'اكتشاف عبر الشبكة'),
  entry('汇聚公开媒体、社交平台与长尾社区信息，清洗多源内容，并把零散线索聚合成可持续跟踪的话题与事件。', 'Bring together public media, social platforms, and long-tail communities, clean mixed-source content, and group scattered signals into trackable topics and events.', 'يجمع الإعلام العام والمنصات الاجتماعية والمجتمعات المتخصصة، وينظف المحتوى متعدد المصادر ويحوّل الإشارات المتفرقة إلى مواضيع وأحداث قابلة للتتبع.'),
  entry('语义理解', 'Semantic understanding', 'فهم دلالي'),
  entry('结合品牌语境判断相关性、情绪、意图、反讽与二次传播，过滤无效命中，把注意力留给真正的品牌风险。', 'Use brand context to assess relevance, sentiment, intent, irony, and secondary spread, filtering false matches so attention stays on real risk.', 'يستخدم سياق العلامة لتقييم الصلة والمشاعر والنية والسخرية والانتشار الثانوي، ويصفي التطابقات غير المفيدة للتركيز على المخاطر الفعلية.'),
  entry('事件研判', 'Event assessment', 'تقييم الأحداث'),
  entry('综合原文证据、账号影响、传播链路与历史参考，给出风险等级、判断依据和置信度，关键结论由负责人复核。', 'Combine source evidence, account influence, propagation paths, and history to provide risk level, rationale, and confidence, with responsible human review.', 'يجمع الأدلة الأصلية وتأثير الحساب ومسار الانتشار والسجل لتحديد مستوى الخطر والمنطق والثقة، مع مراجعة بشرية مسؤولة.'),
  entry('行动建议', 'Action guidance', 'توجيه الإجراءات'),
  entry('围绕事件生成处置策略、回应口径与执行清单，并通过飞书群、微信群等现有协作渠道推送给相关团队。', 'Create response strategy, approved messaging, and an action checklist, then deliver them through existing collaboration channels such as Feishu and WeChat groups.', 'ينشئ استراتيجية الاستجابة والرسائل المعتمدة وقائمة التنفيذ، ثم يرسلها عبر قنوات التعاون الحالية مثل مجموعات Feishu وWeChat.'),
  entry('复盘沉淀', 'Review and retain', 'مراجعة وتراكم'),
  entry('团队的确认、排除、改标签与处置反馈回到专属知识库，让同类事件的下一次判断更快、更贴近品牌标准。', 'Team confirmations, exclusions, label changes, and response feedback return to dedicated knowledge, making the next similar judgment faster and closer to brand standards.', 'تعود تأكيدات الفريق واستبعاده وتعديلاته وملاحظاته إلى المعرفة المخصصة، فيصبح الحكم على الأحداث المشابهة أسرع وأكثر توافقاً مع معايير العلامة.'),
  entry('零散帖子变成事件，', 'Turn scattered posts into events,', 'حوّل المنشورات المتفرقة إلى أحداث،'), entry('事件进入', 'and bring events into ', 'واجمع الأحداث في '), entry('同一个工作台', 'one control center', 'مركز تحكم واحد'),
  entry('总览、话题、事件、可疑账号、多平台热搜与分析报告共享上下文，公关团队不必在不同工具间重复拼接判断。', 'Overview, topics, events, suspicious accounts, cross-platform trends, and reports share context, so PR teams do not rebuild judgment across disconnected tools.', 'تتشارك النظرة العامة والمواضيع والأحداث والحسابات المشبوهة والاتجاهات والتقارير السياق نفسه، فلا يضطر الفريق إلى إعادة تركيب الحكم بين أدوات منفصلة.'),
  entry('不是一张大屏，', 'Not another dashboard,', 'ليست مجرد لوحة معلومات،'), entry('而是一套会', 'but a system that ', 'بل نظام '), entry('完成任务', 'gets work done', 'ينجز العمل'), entry('的系统。', '.', '.'),
  entry('话题监控', 'Topic monitoring', 'مراقبة المواضيع'),
  entry('把长期议题的持续观察与突发事件的主动侦察放在同一视图，按影响力而不是简单声量排序。', 'Keep ongoing observation and active incident detection in one view, prioritized by impact rather than raw volume.', 'يجمع المراقبة المستمرة والكشف النشط عن الأحداث في عرض واحد، ويرتبها حسب التأثير لا الحجم الخام.'),
  entry('事件情报', 'Event intelligence', 'معلومات الأحداث'),
  entry('将零散帖子合并为事件，识别首发源头、关键节点，以及原始内容、二创切片与搬运扩散之间的关系。', 'Group scattered posts into events and identify origin, key nodes, and the relationship between source content, remixes, clips, and reposts.', 'يجمع المنشورات في أحداث ويحدد المصدر والعقد الرئيسية والعلاقة بين المحتوى الأصلي وإعادة الإنتاج والمقاطع وإعادة النشر.'),
  entry('水军雷达', 'Coordinated-account radar', 'رادار الحسابات المنسقة'),
  entry('通过企业专属风险标签辅助识别可疑账号与营销号，持续追踪其活跃话题和平台。', 'Use company-specific risk labels to assist in identifying suspicious and promotional accounts and track their active topics and platforms.', 'يستخدم تسميات مخاطر خاصة بالمؤسسة للمساعدة في تحديد الحسابات المشبوهة والترويجية وتتبع مواضيعها ومنصاتها.'),
  entry('多平台热搜', 'Cross-platform trends', 'اتجاهات متعددة المنصات'),
  entry('聚合不同平台的相关热点与榜单，帮助团队及时看见议题是否发生跨平台迁移。', 'Aggregate relevant trends and rankings so teams can see when an issue moves between platforms.', 'يجمع الاتجاهات والترتيبات ذات الصلة ليكشف انتقال القضية بين المنصات في الوقت المناسب.'),
  entry('分析报告', 'Analysis reports', 'تقارير تحليلية'),
  entry('以结论先行的结构化报告呈现趋势、风险判断和行动建议，并可按企业模板与品牌视觉配置。', 'Present trends, risk judgments, and actions in structured, conclusion-first reports configurable to company templates and brand visuals.', 'يعرض الاتجاهات وتقييم المخاطر والإجراءات في تقارير منظمة تبدأ بالخلاصة ويمكن تخصيصها لقوالب المؤسسة وهوية العلامة.'),
  entry('舆情专家 Agent', 'PR intelligence agent', 'وكيل ذكاء العلاقات العامة'),
  entry('通过对话导入内容、调整关注重点和发起追踪任务；智能体持续汇总、优先推送并形成每日总结。', 'Import content, adjust priorities, and launch tracking tasks through conversation; the agent continuously summarizes, prioritizes alerts, and produces daily reviews.', 'استورد المحتوى وعدّل الأولويات وابدأ مهام التتبع عبر المحادثة؛ يجمع الوكيل النتائج باستمرار ويرتب التنبيهات ويصدر ملخصاً يومياً.'),
  entry('每一次人工判断，', 'Every human judgment', 'كل حكم بشري'), entry('都成为品牌自己的', 'becomes the brand’s own ', 'يصبح أصلاً خاصاً بالعلامة: '), entry('公关资产', 'PR asset', 'أصل علاقات عامة'),
  entry('启晓将历史事件、品牌口径、合规红线与团队反馈沉淀到企业专属知识库。系统不是固定交付后停止变化，而是在明确的人机边界内持续吸收判断力。', 'Qixiao retains historical events, brand messaging, compliance boundaries, and team feedback in dedicated company knowledge. It continues to absorb judgment within clear human–AI boundaries.', 'يحفظ Qixiao الأحداث التاريخية ورسائل العلامة وحدود الامتثال وملاحظات الفريق في معرفة مخصصة للمؤسسة، ويواصل استيعاب الأحكام ضمن حدود واضحة بين الإنسان والذكاء الاصطناعي.'),
  entry('品牌专属模型', 'Brand-specific model', 'نموذج خاص بالعلامة'), entry('客户知识库', 'Company knowledge base', 'قاعدة معرفة المؤسسة'), entry('Agent 工作流', 'Agent workflows', 'سير عمل الوكلاء'), entry('持续反馈', 'Continuous feedback', 'تغذية راجعة مستمرة'),
  entry('适合风险语境复杂、', 'Built for complex risk contexts', 'مصمم لسياقات مخاطر معقدة'), entry('需要跨团队协同的', 'and cross-team ', 'وتعاون '), entry('企业与品牌', 'enterprises and brands', 'المؤسسات والعلامات التجارية'),
  entry('内容与社区平台', 'Content and community platforms', 'منصات المحتوى والمجتمعات'),
  entry('同时面对用户生态、内容合规、商业化争议与跨圈层传播，需要理解平台黑话、二创和社区语境。', 'Manage user ecosystems, content compliance, monetization disputes, and cross-community spread by understanding platform language, remixes, and community context.', 'تتعامل مع منظومة المستخدمين وامتثال المحتوى والجدل التجاري والانتشار بين المجتمعات، مع فهم لغة المنصة وإعادة الإنتاج وسياق المجتمع.'),
  entry('上市公司与硬科技', 'Public companies and frontier tech', 'الشركات المدرجة والتقنية المتقدمة'),
  entry('需要共同观察媒体、投资者社区、监管口径和行业观点，并保留完整证据支持审慎判断。', 'Observe media, investor communities, regulatory language, and industry views together while retaining complete evidence for careful judgment.', 'راقب الإعلام ومجتمعات المستثمرين ولغة الجهات التنظيمية وآراء الصناعة مع الاحتفاظ بأدلة كاملة لدعم الحكم المتأني.'),
  entry('高关注消费品牌', 'High-attention consumer brands', 'العلامات الاستهلاكية عالية الاهتمام'),
  entry('产品安全、服务体验与社交内容容易相互放大，需要尽早识别隐性风险与跨平台扩散。', 'Product safety, service experience, and social content can amplify one another, requiring early detection of hidden risk and cross-platform spread.', 'قد تضخم سلامة المنتج وتجربة الخدمة والمحتوى الاجتماعي بعضها بعضاً، مما يتطلب اكتشاف المخاطر الخفية والانتشار بين المنصات مبكراً.'),
  entry('不止告诉你发生了什么，', 'Go beyond what happened.', 'تجاوز وصف ما حدث.'), entry('更把', 'Make the ', 'وضّح '), entry('下一步依据', 'basis for the next step', 'أساس الخطوة التالية'), entry('说清楚。', ' clear.', ' بوضوح.'),
  entry('报告以多维分析、传播演化和风险评估为基础，结构化呈现证据、重点与建议。模板和视觉可按企业需要配置，便于管理层快速阅读与团队协同。', 'Reports structure evidence, priorities, and recommendations using multidimensional analysis, spread evolution, and risk assessment. Templates and visuals can match company needs for fast executive reading and team coordination.', 'تنظم التقارير الأدلة والأولويات والتوصيات بناءً على تحليل متعدد الأبعاد وتطور الانتشار وتقييم المخاطر. ويمكن تخصيص القوالب والمرئيات لقراءة الإدارة السريعة وتنسيق الفريق.'),
])
