export const seoLandingContent = {
  salesIntelligence: {
    zh: {
      kicker: 'SALES INTELLIGENCE FROM CONVERSATIONS',
      title: '把客户对话转化为\n可行动的第一方销售情报。',
      intro: '销售情报既可以来自外部公司、联系人与意向数据，也可以来自企业自己的客户互动。TellWin 聚焦后一类：把面对面沟通、企业微信等真实对话整理为客户档案、购买信号、异议、待办、辅导依据和跨团队客户声音。它不是联系人数据库，也不只是录音转写。',
      primaryAction: '预约销售场景诊断',
      secondaryAction: '查看 TellWin 产品',
      problemsTitle: '销售情报为什么不能只依赖联系人数据库和 CRM？',
      problemsIntro: '外部数据帮助团队判断“应该联系谁”，CRM 记录“推进到了哪里”，客户对话则解释“买家为什么行动或犹豫”。TellWin 补足的是已经进入真实销售过程后的第一方语境。',
      problems: [
        ['客户信息依赖手工填写', '销售结束沟通后再补录，容易遗漏预算、决策人、竞品、真实异议和承诺事项。'],
        ['优秀经验留在少数人身上', '高绩效销售的提问、倾听和异议处理难以被团队看见，新人辅导只能依赖抽象复盘。'],
        ['客户原声到不了决策层', '一线需求经过多次转述，产品、市场和管理层看到的是结论，而不是可以核验的客户语境。'],
      ],
      processTitle: '从对话到行动的四个步骤',
      processIntro: '每一步都保留原始语境和人工确认边界，让 AI 提高整理与发现效率，不替代销售和管理者作最终判断。',
      process: [
        ['01', '连接沟通入口', '在获得授权并明确数据边界的前提下，接入面对面录音、企业微信或现有业务系统。'],
        ['02', '识别关键信息', '提取客户诉求、预算、角色、时间计划、购买信号、异议、竞品提及和跟进事项。'],
        ['03', '进入业务动作', '为销售生成摘要和下一步，为主管形成辅导线索，并把结构化结果写入 CRM 或飞书。'],
        ['04', '形成组织洞察', '跨对话观察需求、流失原因、话术表现和产品反馈，让客户原声进入经营复盘。'],
      ],
      valueTitle: '同一份客户情报，服务三个角色',
      value: [
        ['一线销售', '减少整理时间，快速回顾客户上下文、承诺与下一步。'],
        ['销售主管', '从真实对话定位团队共性问题，让辅导有具体依据。'],
        ['产品与市场', '持续看见客户需求、竞品比较和反复出现的反馈。'],
      ],
      fitTitle: '什么团队最适合先做试点？',
      fit: ['客单价高、成交依赖深度沟通', '销售周期长、多人参与决策', '客户资产容易随人员流动', '已有 CRM，但一线记录质量不稳定', '希望从真实数据开始验证 AI，而不是先换整套系统'],
      faqTitle: '销售对话智能常见问题',
      faqs: [
        ['TellWin 是联系人数据库或获客平台吗？', '不是。TellWin 不以售卖联系人或外部企业数据为核心，而是从企业已获授权的客户对话中生成第一方销售情报；它可以与外部销售情报和 CRM 数据配合使用。'],
        ['它和录音转写工具有什么区别？', '转写解决“说了什么”，TellWin 进一步识别客户状态、业务信号、行动事项与跨对话趋势，并把结果接回销售流程。'],
        ['必须替换现有 CRM 吗？', '不需要。可以先从一个团队或一种沟通入口开始，将结果写回现有 CRM、飞书多维表格或其他业务系统。'],
        ['如何处理隐私与授权？', '试点前会明确采集告知、数据用途、权限、保存周期与脱敏要求；敏感行业可进一步讨论私有化和区域化部署。'],
        ['多久能判断是否值得继续？', '先选一个业务目标明确、数据可获得的小范围场景，用真实使用和评测结果决定是否扩展，不预设统一周期。'],
      ],
      proofNote: '页面描述为 TellWin 当前可公开的产品能力与实施方法。实际接入范围和效果取决于数据基础、合规要求与团队使用方式。',
    },
    en: {
      kicker: 'SALES INTELLIGENCE FROM CONVERSATIONS',
      title: 'Turn customer conversations\ninto actionable first-party sales intelligence.',
      intro: 'Sales intelligence can come from external company, contact and intent data or from a company’s own customer interactions. TellWin focuses on the latter: it structures real conversations from in-person meetings, private messaging and existing systems into customer records, buyer signals, objections, follow-ups, coaching evidence and customer insight. It is not a contact database and goes beyond transcription.',
      primaryAction: 'Book a sales workflow diagnosis',
      secondaryAction: 'Explore TellWin',
      problemsTitle: 'Why can’t sales intelligence rely on contact data and CRM alone?',
      problemsIntro: 'External data helps teams decide who to contact, CRM records where an opportunity stands, and customer conversations explain why a buyer acts or hesitates. TellWin fills the first-party context gap after a real sales process begins.',
      problems: [
        ['Critical context depends on manual entry', 'Post-call updates often miss budget, decision roles, competitors, real objections and commitments.'],
        ['Winning behavior stays with a few people', 'The questions, listening and objection handling of top performers remain hard to observe and difficult to teach.'],
        ['Customer voice never reaches decision-makers', 'After repeated retelling, product and marketing teams receive conclusions without the original, verifiable context.'],
      ],
      processTitle: 'Four steps from conversation to action',
      processIntro: 'Each step preserves source context and human review. AI accelerates organization and discovery; salespeople and leaders retain the final judgment.',
      process: [
        ['01', 'Connect communication sources', 'With clear consent and data boundaries, connect in-person recordings, private messaging or existing business systems.'],
        ['02', 'Identify business signals', 'Extract needs, budget, stakeholders, timing, buying signals, objections, competitor mentions and follow-up actions.'],
        ['03', 'Return insight to the workflow', 'Give salespeople summaries, managers coaching evidence, and write structured outcomes into CRM or collaboration tools.'],
        ['04', 'Build organizational intelligence', 'Analyze recurring needs, loss reasons, sales behavior and product feedback across conversations.'],
      ],
      valueTitle: 'One customer intelligence asset, three teams',
      value: [
        ['Sales representatives', 'Spend less time organizing notes and recover customer context, commitments and next actions quickly.'],
        ['Sales managers', 'Coach from real conversations and identify recurring team-level gaps.'],
        ['Product and marketing', 'Continuously see customer needs, competitor comparisons and repeated feedback.'],
      ],
      fitTitle: 'Which teams should pilot first?',
      fit: ['High-value purchases depend on consultative conversations', 'Long sales cycles involve several decision-makers', 'Customer relationships are vulnerable to staff turnover', 'A CRM exists, but frontline data quality is inconsistent', 'The team wants to validate AI with real data before replacing core systems'],
      faqTitle: 'Sales conversation intelligence FAQ',
      faqs: [
        ['Is TellWin a contact database or prospecting platform?', 'No. TellWin does not sell contact or external company data. It creates first-party sales intelligence from customer conversations your organization is authorized to use, and can complement external sales intelligence and CRM data.'],
        ['How is this different from transcription?', 'Transcription captures what was said. TellWin identifies customer state, business signals, actions and cross-conversation patterns, then returns them to the sales workflow.'],
        ['Do we need to replace our CRM?', 'No. A pilot can start with one team or communication source and write structured results into the CRM or collaboration system you already use.'],
        ['How do you handle privacy and consent?', 'Before a pilot, we define notice and consent, purpose, access, retention and redaction. Private or regional deployment can be assessed for sensitive environments.'],
        ['How quickly can we evaluate a pilot?', 'Start with one measurable workflow and real data, then decide whether to expand from observed adoption and evaluation results rather than a fixed promise.'],
      ],
      proofNote: 'This page describes currently public TellWin capabilities and implementation methods. Integration scope and outcomes depend on data readiness, compliance requirements and team adoption.',
    },
    ar: {
      kicker: 'ذكاء المبيعات من المحادثات',
      title: 'حوّل محادثات العملاء\nإلى ذكاء مبيعات قابل للتنفيذ من الطرف الأول.',
      intro: 'قد يأتي ذكاء المبيعات من بيانات الشركات وجهات الاتصال والنية الخارجية أو من تفاعلات المؤسسة مع عملائها. تركز TellWin على النوع الثاني، فتنظم المحادثات الفعلية إلى ملفات عملاء وإشارات شراء واعتراضات ومتابعة وأدلة تدريب ورؤى مشتركة. وهي ليست قاعدة بيانات لجهات الاتصال وتتجاوز النسخ النصي.',
      primaryAction: 'احجز تشخيصاً لسير المبيعات',
      secondaryAction: 'استكشف TellWin',
      problemsTitle: 'لماذا لا يكفي الاعتماد على بيانات الاتصال وCRM لذكاء المبيعات؟',
      problemsIntro: 'تساعد البيانات الخارجية في اختيار من نتواصل معه، ويسجل CRM مرحلة الفرصة، بينما تفسر محادثات العملاء سبب تصرف المشتري أو تردده. وتملأ TellWin فجوة السياق من الطرف الأول بعد بدء عملية البيع الفعلية.',
      problems: [
        ['السياق المهم يعتمد على الإدخال اليدوي', 'غالباً ما تفقد التحديثات اللاحقة الميزانية وأصحاب القرار والمنافسين والاعتراضات والالتزامات.'],
        ['خبرة الأداء العالي تبقى لدى أفراد محدودين', 'يصعب ملاحظة أسئلة أفضل البائعين وطريقة استماعهم ومعالجة الاعتراضات وتحويلها إلى تدريب للفريق.'],
        ['صوت العميل لا يصل إلى صانع القرار', 'بعد تكرار نقل المعلومات تصل إلى فرق المنتج والتسويق استنتاجات من دون السياق الأصلي القابل للتحقق.'],
      ],
      processTitle: 'أربع خطوات من المحادثة إلى الإجراء',
      processIntro: 'تحافظ كل خطوة على المصدر والمراجعة البشرية. يسرّع الذكاء الاصطناعي التنظيم والاكتشاف، بينما يبقى القرار النهائي لدى الفريق.',
      process: [
        ['01', 'ربط مصادر التواصل', 'بعد توضيح الموافقة وحدود البيانات، تُربط التسجيلات الميدانية والرسائل الخاصة أو أنظمة العمل الحالية.'],
        ['02', 'اكتشاف إشارات العمل', 'استخراج الاحتياجات والميزانية والأدوار والتوقيت وإشارات الشراء والاعتراضات والمنافسين وخطوات المتابعة.'],
        ['03', 'إعادة الرؤية إلى سير العمل', 'تقديم ملخصات للبائع وأدلة تدريب للمدير وكتابة النتائج المنظمة في CRM أو أدوات التعاون.'],
        ['04', 'بناء معرفة مؤسسية', 'تحليل الاحتياجات المتكررة وأسباب الخسارة وسلوك المبيعات وملاحظات المنتج عبر المحادثات.'],
      ],
      valueTitle: 'أصل واحد لمعلومات العملاء يخدم ثلاثة فرق',
      value: [
        ['فريق المبيعات', 'تقليل وقت تنظيم الملاحظات واستعادة سياق العميل والالتزامات والخطوة التالية بسرعة.'],
        ['مديرو المبيعات', 'التدريب انطلاقاً من محادثات فعلية واكتشاف الفجوات المشتركة في الفريق.'],
        ['المنتج والتسويق', 'رؤية مستمرة لاحتياجات العملاء ومقارنات المنافسين والملاحظات المتكررة.'],
      ],
      fitTitle: 'من الأنسب لبدء تجربة أولى؟',
      fit: ['عمليات شراء عالية القيمة تعتمد على الحوار الاستشاري', 'دورة مبيعات طويلة تضم عدة أصحاب قرار', 'علاقات العملاء معرضة للتأثر بتغير الموظفين', 'وجود CRM مع تفاوت جودة بيانات الخط الأمامي', 'الرغبة في اختبار الذكاء الاصطناعي ببيانات فعلية قبل استبدال الأنظمة الأساسية'],
      faqTitle: 'أسئلة شائعة حول ذكاء محادثات المبيعات',
      faqs: [
        ['هل TellWin قاعدة بيانات لجهات الاتصال أو منصة للتنقيب؟', 'لا. لا تبيع TellWin بيانات اتصال أو شركات خارجية، بل تنشئ ذكاء مبيعات من الطرف الأول من محادثات العملاء المصرح للمؤسسة باستخدامها، ويمكن أن تكمل بيانات ذكاء المبيعات الخارجية وCRM.'],
        ['ما الفرق بينه وبين النسخ النصي؟', 'النسخ يسجل ما قيل، بينما تحدد TellWin حالة العميل وإشارات العمل والإجراءات والأنماط عبر المحادثات ثم تعيدها إلى سير المبيعات.'],
        ['هل يجب استبدال CRM الحالي؟', 'لا. يمكن أن تبدأ التجربة بفريق أو مصدر تواصل واحد وكتابة النتائج المنظمة في النظام المستخدم حالياً.'],
        ['كيف تتعاملون مع الخصوصية والموافقة؟', 'قبل التجربة نحدد الإشعار والموافقة والغرض والصلاحيات ومدة الاحتفاظ وإخفاء البيانات، مع تقييم النشر الخاص أو الإقليمي عند الحاجة.'],
        ['متى يمكن تقييم التجربة؟', 'نبدأ بسير عمل قابل للقياس وبيانات فعلية، ثم نقرر التوسع بناءً على الاستخدام ونتائج التقييم بدلاً من وعد زمني ثابت.'],
      ],
      proofNote: 'تعرض هذه الصفحة قدرات TellWin وأساليب التنفيذ المتاحة للنشر حالياً. يعتمد نطاق الربط والنتائج على جاهزية البيانات ومتطلبات الامتثال وتبنّي الفريق.',
    },
  },
  salesCallAnalysis: {
    zh: {
      kicker: 'AI SALES CALL ANALYSIS',
      title: '不只转写销售通话，\n还要看懂客户为什么买、为什么犹豫。',
      intro: 'TellWin 将获得授权的销售电话与面对面沟通整理为客户需求、购买信号、异议、竞品提及、承诺事项和下一步，让销售快速跟进，也让主管基于真实语境进行辅导。',
      primaryAction: '讨论销售通话分析试点',
      secondaryAction: '了解 TellWin 产品',
      problemsTitle: '为什么通话录音很多，团队仍然缺少销售洞察？',
      problemsIntro: '录音解决了“有没有留下”，但没有自动解决“谁来听、看什么、如何行动”。如果信息仍靠人工回忆和抽查，关键客户语境依然很难进入销售流程。',
      problems: [
        ['录音难以逐条复听', '主管不可能完整听完所有通话，抽查又容易错过真正需要辅导或及时跟进的对话。'],
        ['摘要缺少业务结构', '通用摘要往往没有区分预算、决策人、购买时点、异议、竞品和承诺事项。'],
        ['分析结果没有进入动作', '即使得到纪要，如果没有进入 CRM、待办和主管复盘，洞察仍停留在一个孤立工具里。'],
      ],
      processTitle: '从一段销售通话到可执行跟进',
      processIntro: '围绕真实销售流程配置字段和评测标准，并保留原始语境与人工确认，不让模型输出直接替代业务判断。',
      process: [
        ['01', '接入获准的通话', '明确客户告知、使用目的、访问权限和保存周期后，连接选定录音或沟通入口。'],
        ['02', '提取销售关键信号', '识别客户诉求、预算、角色、购买时点、异议、竞品、承诺和未回答问题。'],
        ['03', '生成角色化结果', '为销售输出摘要与待办，为主管提供辅导线索，为管理层形成可追溯的趋势视图。'],
        ['04', '回写现有工作流', '将经确认的结构化结果接入 CRM、飞书或团队当前使用的跟进系统。'],
      ],
      valueTitle: '一段通话，形成三种业务价值',
      value: [
        ['销售跟进', '快速恢复客户上下文，明确承诺事项、未回答问题和下一次触达重点。'],
        ['主管辅导', '定位提问、倾听、需求确认和异议处理中的具体片段，而不是只看结果。'],
        ['经营洞察', '跨通话观察客户需求、流失原因、竞品提及和产品反馈的重复模式。'],
      ],
      fitTitle: '哪些通话场景值得先分析？',
      fit: ['客单价高、一次通话包含大量决策信息', '销售周期长、需要多次接续沟通', '主管抽听成本高、辅导缺少依据', '已有录音，但尚未形成结构化客户档案', '能够取得合法授权并明确数据使用边界'],
      faqTitle: 'AI 销售通话分析常见问题',
      faqs: [
        ['它和通话转写有什么区别？', '转写主要回答“说了什么”；TellWin 进一步按销售场景识别客户状态、异议、承诺、下一步和跨通话趋势。'],
        ['会自动给销售打分吗？', '可以围绕企业确认的标准形成评测线索，但不建议用未经校准的模型分数直接替代主管判断或作为单一绩效依据。'],
        ['能接入现有 CRM 吗？', '可以先验证字段、准确性和使用方式，再根据现有系统接口确定回写范围，不要求先替换 CRM。'],
        ['如何保护客户隐私？', '试点前应明确告知与授权、用途、权限、保存和删除规则；实际方案需要结合当地法规与企业制度确认。'],
      ],
      proofNote: '本页描述 TellWin 的目标工作流与公开能力。具体通话来源、识别准确性、系统接入和合规方式须通过真实样本评测与实施确认。',
    },
    en: {
      kicker: 'AI SALES CALL ANALYSIS',
      title: 'Go beyond sales call transcripts\nto understand why buyers act—or hesitate.',
      intro: 'TellWin structures approved sales calls and in-person conversations into needs, buying signals, objections, competitor mentions, commitments and next actions—helping representatives follow up and managers coach from real context.',
      primaryAction: 'Discuss a call analysis pilot',
      secondaryAction: 'Explore TellWin',
      problemsTitle: 'Why do recorded calls still fail to produce sales insight?',
      problemsIntro: 'Recording answers whether the conversation was retained, but not who will review it, what matters or what happens next. Manual recall and occasional sampling still leave important customer context outside the workflow.',
      problems: [
        ['Teams cannot replay every call', 'Managers cannot listen to everything, while random sampling can miss the conversations that need urgent follow-up or coaching.'],
        ['Generic summaries lack sales structure', 'A general recap may not distinguish budget, decision roles, purchase timing, objections, competitors and commitments.'],
        ['Analysis remains disconnected from action', 'Even a useful summary creates little value when it does not reach CRM records, tasks or manager reviews.'],
      ],
      processTitle: 'From one sales call to an actionable follow-up',
      processIntro: 'Configure fields and evaluation criteria around the real workflow, preserve source context and human review, and never let model output replace final business judgment.',
      process: [
        ['01', 'Connect approved conversations', 'Define notice, purpose, access and retention, then connect selected recordings or communication sources.'],
        ['02', 'Extract sales signals', 'Identify needs, budget, stakeholders, timing, objections, competitors, commitments and unanswered questions.'],
        ['03', 'Create role-specific outputs', 'Give representatives summaries and actions, managers coaching evidence, and leaders traceable trend views.'],
        ['04', 'Return results to the workflow', 'Write reviewed structured outcomes into CRM, collaboration tools or the team’s current follow-up system.'],
      ],
      valueTitle: 'One call, three forms of business value',
      value: [
        ['Sales follow-up', 'Recover context quickly and clarify commitments, open questions and the focus of the next contact.'],
        ['Manager coaching', 'Review specific moments in discovery, listening, qualification and objection handling—not outcomes alone.'],
        ['Business insight', 'See recurring needs, loss reasons, competitor mentions and product feedback across conversations.'],
      ],
      fitTitle: 'Which calls are worth analyzing first?',
      fit: ['High-value calls contain substantial decision context', 'Long sales cycles require continuity across conversations', 'Managers spend too much time sampling calls', 'Recordings exist but structured customer records do not', 'The organization can establish lawful consent and data boundaries'],
      faqTitle: 'AI sales call analysis FAQ',
      faqs: [
        ['How is it different from call transcription?', 'Transcription captures what was said. TellWin structures customer state, objections, commitments, next actions and patterns around the sales workflow.'],
        ['Does it automatically score representatives?', 'It can surface evidence against criteria approved by the organization, but uncalibrated model scores should not replace manager judgment or become the sole performance measure.'],
        ['Can it connect to our CRM?', 'Start by validating fields, accuracy and usage, then define the write-back scope from available system interfaces. Replacing the CRM is not required.'],
        ['How is customer privacy handled?', 'A pilot should define notice and consent, purpose, access, retention and deletion. The final approach must reflect local law and company policy.'],
      ],
      proofNote: 'This page describes the target workflow and public TellWin capabilities. Conversation sources, accuracy, integrations and compliance must be confirmed through representative samples and implementation review.',
    },
    ar: {
      kicker: 'تحليل مكالمات المبيعات بالذكاء الاصطناعي',
      title: 'تجاوز نسخ مكالمات المبيعات\nلفهم سبب إقدام المشتري أو تردده.',
      intro: 'تنظّم TellWin مكالمات المبيعات والمحادثات المباشرة المصرح بها إلى احتياجات وإشارات شراء واعتراضات وذكر للمنافسين والتزامات وخطوات تالية، لتساعد البائع على المتابعة والمدير على التدريب من سياق حقيقي.',
      primaryAction: 'ناقش تجربة لتحليل المكالمات',
      secondaryAction: 'استكشف TellWin',
      problemsTitle: 'لماذا لا تنتج المكالمات المسجلة رؤى مبيعات كافية؟',
      problemsIntro: 'يضمن التسجيل الاحتفاظ بالمحادثة، لكنه لا يحدد من يراجعها وما المهم وما الإجراء التالي. لذلك يبقى سياق العميل خارج سير العمل عند الاعتماد على الذاكرة والعينات المحدودة.',
      problems: [
        ['لا يمكن إعادة الاستماع إلى كل مكالمة', 'لا يستطيع المدير سماع كل التسجيلات، وقد تفوّت العينات العشوائية محادثات تحتاج إلى متابعة أو تدريب عاجل.'],
        ['الملخص العام يفتقر إلى بنية المبيعات', 'قد لا يميز الملخص بين الميزانية وأصحاب القرار والتوقيت والاعتراضات والمنافسين والالتزامات.'],
        ['يبقى التحليل منفصلاً عن الإجراء', 'حتى الملخص المفيد يفقد قيمته إذا لم يصل إلى CRM والمهام ومراجعات المدير.'],
      ],
      processTitle: 'من مكالمة مبيعات إلى متابعة قابلة للتنفيذ',
      processIntro: 'تُضبط الحقول ومعايير التقييم وفق سير العمل الفعلي مع الاحتفاظ بالمصدر والمراجعة البشرية، فلا يحل مخرج النموذج محل الحكم المهني النهائي.',
      process: [
        ['01', 'ربط المحادثات المصرح بها', 'تحديد الإشعار والغرض والصلاحيات والاحتفاظ ثم ربط التسجيلات أو مصادر التواصل المختارة.'],
        ['02', 'استخراج إشارات المبيعات', 'تحديد الاحتياجات والميزانية والأطراف والتوقيت والاعتراضات والمنافسين والالتزامات والأسئلة المفتوحة.'],
        ['03', 'إنتاج نتائج حسب الدور', 'ملخصات وإجراءات للبائع وأدلة تدريب للمدير واتجاهات قابلة للتتبع للقيادة.'],
        ['04', 'إعادة النتائج إلى سير العمل', 'كتابة النتائج المنظمة بعد مراجعتها في CRM أو أدوات التعاون أو نظام المتابعة الحالي.'],
      ],
      valueTitle: 'مكالمة واحدة وثلاث قيم للأعمال',
      value: [
        ['متابعة المبيعات', 'استعادة السياق وتوضيح الالتزامات والأسئلة المفتوحة ومحور الاتصال التالي.'],
        ['تدريب المدير', 'مراجعة لحظات محددة في الاستكشاف والاستماع والتأهيل ومعالجة الاعتراضات بدلاً من النتائج فقط.'],
        ['رؤية الأعمال', 'اكتشاف الاحتياجات وأسباب الخسارة والمنافسين وملاحظات المنتج المتكررة عبر المحادثات.'],
      ],
      fitTitle: 'ما المكالمات الأنسب للبدء؟',
      fit: ['مكالمات عالية القيمة تضم سياقاً مهماً للقرار', 'دورات مبيعات طويلة تحتاج إلى استمرارية', 'ارتفاع تكلفة الاستماع اليدوي لدى المديرين', 'وجود تسجيلات من دون ملفات عملاء منظمة', 'إمكانية تأسيس موافقة قانونية وحدود واضحة للبيانات'],
      faqTitle: 'أسئلة شائعة حول تحليل مكالمات المبيعات',
      faqs: [
        ['ما الفرق بينه وبين النسخ النصي؟', 'يسجل النسخ ما قيل، بينما تنظّم TellWin حالة العميل والاعتراضات والالتزامات والخطوات التالية والأنماط وفق سير المبيعات.'],
        ['هل يقيّم البائعين تلقائياً؟', 'يمكنه إظهار أدلة وفق معايير تعتمدها المؤسسة، لكن لا ينبغي أن تستبدل الدرجات غير المعايرة حكم المدير أو تكون مقياس الأداء الوحيد.'],
        ['هل يمكن ربطه مع CRM؟', 'نبدأ بتقييم الحقول والدقة والاستخدام ثم نحدد نطاق الكتابة وفق واجهات النظام المتاحة، من دون ضرورة استبدال CRM.'],
        ['كيف تُحمى خصوصية العميل؟', 'يجب تحديد الإشعار والموافقة والغرض والصلاحيات والاحتفاظ والحذف، وأن يعكس التنفيذ القانون المحلي وسياسة المؤسسة.'],
      ],
      proofNote: 'تصف الصفحة سير العمل المستهدف وقدرات TellWin العامة. يجب تأكيد مصادر المحادثات والدقة والتكامل والامتثال بعينات ممثلة ومراجعة التنفيذ.',
    },
  },
  automotive: {
    zh: {
      kicker: 'AUTOMOTIVE SALES AI',
      title: '让每一次试驾与门店沟通，\n都成为下一步成交的客户依据。',
      intro: 'TellWin 面向汽车经销商和品牌销售团队，将获准采集的展厅、试驾与跟进沟通整理为车型偏好、预算、置换、配置关注、竞品比较、家庭决策和下一步，帮助顾问连续跟进，也帮助管理者看见真实客户声音。',
      primaryAction: '讨论汽车销售试点',
      secondaryAction: '了解销售对话智能',
      problemsTitle: '为什么试驾结束后，最重要的客户信息容易消失？',
      problemsIntro: '汽车购买同时包含产品、价格、金融、置换和家庭意见。只记录“意向车型”和“跟进状态”，不足以让下一次沟通真正接续客户的决策过程。',
      problems: [
        ['需求藏在长对话里', '配置、空间、续航、操控、交付和用车场景交织在一起，手工备注很难完整保留。'],
        ['“再考虑”没有被解释', '价格、竞品、家庭意见、置换估值或金融方案都可能是真实阻力，但系统里常只剩模糊状态。'],
        ['门店经验难以复制', '优秀顾问如何提问、介绍和处理异议很难被系统看见，新人辅导依赖个人经验。'],
      ],
      processTitle: '汽车销售客户情报的四个步骤',
      processIntro: '从一个门店或团队开始，选定合法合规的沟通入口与可衡量的跟进任务，再决定是否扩大范围。',
      process: [
        ['01', '采集获准的销售沟通', '明确客户告知与权限边界后，连接展厅接待、试驾复盘或后续电话等选定场景。'],
        ['02', '生成购车客户画像', '识别车型、配置、预算、金融、置换、使用场景、决策人、竞品、顾虑和计划时间。'],
        ['03', '辅助顾问继续跟进', '形成摘要、待办、未确认信息和下一次触达重点，减少重复询问与交接损失。'],
        ['04', '汇总门店与产品洞察', '跨对话观察客户关注、流失原因、竞品反馈和辅导主题，为管理复盘提供语境。'],
      ],
      valueTitle: '服务顾问、门店经理与品牌团队',
      value: [
        ['销售顾问', '快速回顾客户完整语境，让报价、邀约和后续沟通更连续。'],
        ['门店经理', '从真实接待片段定位辅导机会，而不只依赖销量和活动量。'],
        ['品牌与产品团队', '持续看见配置关注、竞品比较、价格反馈和真实使用场景。'],
      ],
      fitTitle: '哪些汽车销售团队适合先验证？',
      fit: ['试驾和门店沟通对成交影响大', '车型、配置、金融和置换信息复杂', '同一客户由多人或多渠道接续', '已有 CRM，但备注仍依赖顾问手工填写', '希望以真实接待样本验证准确性和采用情况'],
      faqTitle: '汽车销售 AI 常见问题',
      faqs: [
        ['TellWin 是汽车 CRM 吗？', '不是。TellWin 聚焦对话理解与客户情报，可把经确认的结构化结果接回现有 CRM 或门店系统。'],
        ['能识别车型和行业术语吗？', '可以围绕品牌、车型、配置和业务词汇建立评测与配置，但具体准确性需要用代表性真实样本验证。'],
        ['会自动联系客户吗？', '默认先为顾问生成摘要、待办和建议，由人员确认后执行；自动化范围取决于渠道、规则和合规边界。'],
        ['试点应该从哪里开始？', '选择一个门店、一个沟通场景和一组明确任务，对识别质量、跟进使用和管理价值进行真实评测。'],
      ],
      proofNote: '本页描述汽车销售目标场景与实施方法，不代表已与所有汽车品牌、门店系统或沟通渠道完成标准化接入，最终范围以试点评测为准。',
    },
    en: {
      kicker: 'AUTOMOTIVE SALES AI',
      title: 'Turn every test drive and showroom conversation\ninto evidence for the next sales action.',
      intro: 'TellWin helps automotive retailers and brand sales teams structure approved showroom, test-drive and follow-up conversations into model preferences, budget, trade-in, feature priorities, competitor comparisons, household decisions and next actions.',
      primaryAction: 'Discuss an automotive sales pilot',
      secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why does critical buyer context disappear after the test drive?',
      problemsIntro: 'A vehicle purchase combines product, pricing, finance, trade-in and household input. Recording only the preferred model and follow-up status cannot preserve the buyer’s full decision process.',
      problems: [
        ['Needs are buried in long conversations', 'Features, space, range, handling, delivery and driving scenarios overlap, making complete manual notes difficult.'],
        ['“Still considering” remains unexplained', 'Price, competitors, family input, trade-in valuation or finance may be the real barrier, while the system keeps only a vague status.'],
        ['Showroom expertise is hard to replicate', 'The discovery, explanation and objection handling of strong advisors remain difficult to observe and teach.'],
      ],
      processTitle: 'Four steps for automotive customer intelligence',
      processIntro: 'Start with one showroom or team, a compliant communication source and measurable follow-up tasks, then expand only after real evaluation.',
      process: [
        ['01', 'Capture approved sales conversations', 'With clear notice and permissions, connect selected showroom, test-drive review or follow-up call scenarios.'],
        ['02', 'Build the vehicle buyer profile', 'Identify model, features, budget, finance, trade-in, use case, decision roles, competitors, concerns and timing.'],
        ['03', 'Support advisor follow-up', 'Create summaries, actions, missing information and the focus for the next contact to reduce repetition and handoff loss.'],
        ['04', 'Aggregate showroom and product insight', 'Observe recurring interests, loss reasons, competitor feedback and coaching themes with traceable context.'],
      ],
      valueTitle: 'Value for advisors, showroom managers and brand teams',
      value: [
        ['Sales advisors', 'Recover the complete buyer context so quotations, appointments and follow-ups remain continuous.'],
        ['Showroom managers', 'Find coaching opportunities in real interactions instead of relying only on sales and activity counts.'],
        ['Brand and product teams', 'Continuously see feature priorities, competitor comparisons, price feedback and real use cases.'],
      ],
      fitTitle: 'Which automotive teams should validate first?',
      fit: ['Test drives and showroom conversations strongly influence decisions', 'Model, feature, finance and trade-in information is complex', 'Customers move between people or channels', 'CRM exists but notes still depend on manual entry', 'The team can evaluate accuracy and adoption with representative interactions'],
      faqTitle: 'Automotive sales AI FAQ',
      faqs: [
        ['Is TellWin an automotive CRM?', 'No. TellWin focuses on conversation understanding and customer intelligence, returning reviewed structured outcomes to an existing CRM or retail system.'],
        ['Can it recognize models and automotive terms?', 'Evaluation and configuration can cover brand, model, feature and workflow vocabulary, but accuracy must be validated with representative real samples.'],
        ['Will it contact customers automatically?', 'The default is to produce summaries, actions and suggestions for advisor review. Automation depends on channels, business rules and compliance.'],
        ['Where should a pilot begin?', 'Choose one showroom, one conversation scenario and clear tasks, then evaluate recognition quality, adoption and management value in real work.'],
      ],
      proofNote: 'This page describes the target automotive workflow and implementation approach. It does not claim standardized integration with every brand, retail system or communication channel; final scope depends on pilot evaluation.',
    },
    ar: {
      kicker: 'الذكاء الاصطناعي لمبيعات السيارات',
      title: 'حوّل كل تجربة قيادة ومحادثة في المعرض\nإلى أساس واضح للخطوة البيعية التالية.',
      intro: 'تساعد TellWin وكلاء السيارات وفرق مبيعات العلامات على تنظيم محادثات المعرض وتجربة القيادة والمتابعة المصرح بها إلى تفضيلات الطراز والميزانية والاستبدال والمواصفات والمنافسين وقرار الأسرة والخطوات التالية.',
      primaryAction: 'ناقش تجربة لمبيعات السيارات',
      secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا يختفي سياق المشتري المهم بعد تجربة القيادة؟',
      problemsIntro: 'يجمع شراء السيارة بين المنتج والسعر والتمويل والاستبدال ورأي الأسرة. ولا يكفي تسجيل الطراز المفضل وحالة المتابعة للاحتفاظ بمسار القرار كاملاً.',
      problems: [
        ['الاحتياجات مدفونة في حوار طويل', 'تتداخل المواصفات والمساحة والمدى والقيادة والتسليم والاستخدام، فيصعب تدوينها يدوياً بصورة كاملة.'],
        ['عبارة «ما زلت أفكر» بلا تفسير', 'قد يكون السعر أو المنافس أو الأسرة أو تقييم الاستبدال أو التمويل هو العائق الحقيقي، بينما يبقى في النظام وصف مبهم.'],
        ['يصعب نقل خبرة المعرض', 'تبقى طريقة أفضل المستشارين في الاستكشاف والشرح ومعالجة الاعتراضات صعبة الملاحظة والتعليم.'],
      ],
      processTitle: 'أربع خطوات لمعلومات عملاء السيارات',
      processIntro: 'ابدأ بمعرض أو فريق واحد ومصدر تواصل متوافق ومهام متابعة قابلة للقياس، ثم توسع بعد التقييم الفعلي فقط.',
      process: [
        ['01', 'جمع محادثات البيع المصرح بها', 'بعد توضيح الإشعار والصلاحيات، تُربط مواقف مختارة في المعرض أو تجربة القيادة أو مكالمات المتابعة.'],
        ['02', 'إنشاء ملف مشتري السيارة', 'تحديد الطراز والمواصفات والميزانية والتمويل والاستبدال والاستخدام والأطراف والمنافسين والمخاوف والتوقيت.'],
        ['03', 'دعم متابعة المستشار', 'إنتاج ملخصات ومهام ومعلومات ناقصة ومحور الاتصال التالي لتقليل التكرار وفقدان السياق.'],
        ['04', 'تجميع رؤى المعرض والمنتج', 'رصد الاهتمامات وأسباب الخسارة وملاحظات المنافسين وموضوعات التدريب المتكررة بسياق قابل للتتبع.'],
      ],
      valueTitle: 'قيمة للمستشار ومدير المعرض وفريق العلامة',
      value: [
        ['مستشارو المبيعات', 'استعادة سياق المشتري كاملاً لاستمرار العروض والمواعيد والمتابعة.'],
        ['مديرو المعارض', 'اكتشاف فرص التدريب من تفاعلات حقيقية بدلاً من أرقام المبيعات والنشاط فقط.'],
        ['فرق العلامة والمنتج', 'رؤية مستمرة لأولويات المواصفات والمنافسين والأسعار وحالات الاستخدام الفعلية.'],
      ],
      fitTitle: 'أي فرق سيارات أنسب للتقييم الأول؟',
      fit: ['تأثير تجربة القيادة وحوار المعرض في القرار', 'تعقيد معلومات الطراز والمواصفات والتمويل والاستبدال', 'انتقال العميل بين عدة أشخاص أو قنوات', 'وجود CRM مع اعتماد الملاحظات على الإدخال اليدوي', 'إمكانية تقييم الدقة والاستخدام بتفاعلات ممثلة'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات السيارات',
      faqs: [
        ['هل TellWin نظام CRM للسيارات؟', 'لا. تركز TellWin على فهم المحادثة ومعلومات العميل، وتعيد النتائج المنظمة بعد مراجعتها إلى CRM أو نظام التجزئة الحالي.'],
        ['هل يتعرف على الطرازات ومصطلحات السيارات؟', 'يمكن أن يغطي التقييم والإعداد العلامات والطرازات والمواصفات ومفردات العمل، لكن يجب تأكيد الدقة بعينات فعلية ممثلة.'],
        ['هل سيتواصل مع العميل تلقائياً؟', 'الوضع الافتراضي هو إنتاج ملخصات ومهام واقتراحات يراجعها المستشار، وتعتمد الأتمتة على القنوات والقواعد والامتثال.'],
        ['من أين تبدأ التجربة؟', 'اختر معرضاً وسيناريو محادثة ومهام واضحة، ثم قيّم جودة الاستخراج والاستخدام والقيمة الإدارية في العمل الفعلي.'],
      ],
      proofNote: 'تصف الصفحة سير العمل المستهدف لمبيعات السيارات ونهج التنفيذ، ولا تدّعي تكاملاً موحداً مع كل علامة أو نظام أو قناة. يعتمد النطاق النهائي على تقييم التجربة.',
    },
  },
  jewelry: {
    zh: {
      kicker: 'JEWELRY SALES AI',
      title: '让每一次珠宝顾问沟通，\n都成为可延续的客户关系资产。',
      intro: 'TellWin 面向高端珠宝、定制珠宝与门店顾问团队，将面谈和企业微信沟通中的预算、场合、款式、材质、尺寸、偏好、顾虑与承诺事项整理为客户上下文。顾问可以更准确地接续服务，主管也能从真实语境中辅导团队。',
      primaryAction: '讨论珠宝销售试点', secondaryAction: '了解销售对话智能',
      problemsTitle: '珠宝销售为什么尤其依赖完整客户语境？',
      problemsIntro: '高价值珠宝成交往往跨越多次咨询、试戴、家庭讨论与方案调整。只记录联系方式和意向等级，无法承载审美偏好、情感用途、预算边界和顾虑变化。',
      problems: [['需求藏在多轮沟通里', '纪念日、婚礼、收藏或送礼等用途，会影响款式、材质、预算和决策节奏，零散备注很难保留完整关联。'], ['优秀服务经验难以复制', '资深顾问如何提问、理解审美、解释工艺和处理价格顾虑，通常只存在于个人经验中。'], ['交接容易让体验断层', '顾问轮班或客户跨门店沟通时，如果团队看不到此前承诺与偏好，客户需要重复说明，信任也会受损。']],
      processTitle: '从顾问对话到持续跟进的四个步骤',
      processIntro: '以客户知情、权限边界和人工复核为前提，从一个门店或一种沟通渠道开始验证，不要求先替换现有会员或零售系统。',
      process: [['01', '接入获授权的沟通', '在明确告知、用途和保存规则后，接入面谈录音、企业微信或选定的业务记录。'], ['02', '整理客户偏好与信号', '识别用途、预算、款式、材质、尺寸、时间计划、参与决策人、顾虑、竞品与购买信号。'], ['03', '形成顾问跟进动作', '生成可复核摘要、待确认问题、承诺事项与下一步建议，帮助顾问延续客户语境。'], ['04', '沉淀团队服务洞察', '跨对话观察常见需求、异议、产品反馈和辅导机会，让一线经验进入团队复盘。']],
      valueTitle: '同一份客户语境，连接销售与经营',
      value: [['珠宝顾问', '快速恢复客户偏好与此前承诺，减少重复整理并保持服务连续性。'], ['门店与销售主管', '从真实对话发现辅导机会、跟进断点和团队共性问题。'], ['商品与品牌团队', '在保护客户隐私的前提下，看见反复出现的款式需求、材质关注和产品反馈。']],
      fitTitle: '哪些珠宝团队适合先试点？',
      fit: ['高端珠宝、婚庆珠宝或定制珠宝销售', '成交依赖多轮咨询、试戴与方案调整', '使用企业微信或会员系统，但对话语境仍靠顾问手工记录', '希望将资深顾问经验转化为具体辅导依据', '能够建立客户告知、数据权限与人工复核机制'],
      faqTitle: '珠宝销售 AI 常见问题',
      faqs: [['TellWin 是珠宝门店 CRM 吗？', '不是。TellWin 重点理解销售对话并形成客户情报，可将复核后的结构化结果接回现有 CRM、会员系统或协作工具。'], ['能识别款式、材质和珠宝术语吗？', '可以围绕企业自己的产品资料和业务词汇进行配置，但具体术语、方言和场景准确度必须用代表性真实样本评估。'], ['会自动替顾问回复客户吗？', '默认先生成摘要、待办和建议，由顾问审核。是否进一步自动化取决于渠道规则、业务边界与合规要求。'], ['是否已有珠宝场景验证？', '我们已在匿名化的高端珠宝定制场景完成付费交付，围绕企业微信真实成交记录构建销售知识与话术分析能力；不同企业仍需独立评估。']],
      proofNote: 'TellWin 已在匿名化珠宝定制场景完成付费交付。页面不披露客户身份、经营数据或未经验证的效果指标；实际范围取决于数据、合规与试点评估。',
    },
    en: {
      kicker: 'JEWELRY SALES AI',
      title: 'Turn every jewelry consultation\ninto continuous client intelligence.',
      intro: 'TellWin helps luxury, bridal and custom jewelry teams structure budget, occasion, style, materials, sizing, preferences, concerns and commitments from consultations and approved private-channel conversations. Advisors can continue service with context while managers coach from real interactions.',
      primaryAction: 'Discuss a jewelry sales pilot', secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why does jewelry sales depend on complete client context?',
      problemsIntro: 'A high-value jewelry decision can span consultations, try-ons, family discussions and design revisions. Contact details and intent scores cannot preserve aesthetic preferences, emotional purpose, budget boundaries or changing concerns.',
      problems: [['Needs emerge across several conversations', 'Anniversaries, weddings, collecting and gifting shape design, material, budget and timing in ways fragmented notes rarely connect.'], ['Exceptional service is difficult to replicate', 'How experienced advisors discover taste, explain craftsmanship and handle price concerns usually remains personal knowledge.'], ['Handoffs break the client experience', 'When shifts or stores change, missing preferences and commitments force clients to repeat themselves and weaken trust.']],
      processTitle: 'Four steps from consultation to continuous follow-up',
      processIntro: 'Start with clear notice, access boundaries and human review in one store or channel. A pilot does not require replacing the existing CRM, clienteling or retail system.',
      process: [['01', 'Connect approved conversations', 'With defined notice, purpose and retention, connect consultation recordings, private messaging or selected business records.'], ['02', 'Structure preferences and signals', 'Identify occasion, budget, style, material, size, timing, decision participants, concerns, competitors and buying signals.'], ['03', 'Create advisor follow-up actions', 'Generate reviewable summaries, open questions, commitments and next-step suggestions that preserve client context.'], ['04', 'Build team service intelligence', 'Find recurring needs, objections, product feedback and coaching opportunities across conversations.']],
      valueTitle: 'One client context connecting sales and operations',
      value: [['Jewelry advisors', 'Recover preferences and commitments quickly, reduce note-taking and maintain continuity.'], ['Store and sales managers', 'Find coaching opportunities, follow-up gaps and recurring team issues in real conversations.'], ['Merchandising and brand teams', 'See recurring design, material and product feedback while maintaining privacy boundaries.']],
      fitTitle: 'Which jewelry teams should pilot first?',
      fit: ['Luxury, bridal or custom jewelry sales', 'Decisions require several consultations, try-ons or design revisions', 'CRM or clienteling exists but conversation context remains manual', 'Leaders want concrete coaching evidence from experienced advisors', 'The business can establish notice, access and human-review controls'],
      faqTitle: 'Jewelry sales AI FAQ',
      faqs: [['Is TellWin a jewelry retail CRM?', 'No. TellWin focuses on conversation understanding and client intelligence, returning reviewed structured outcomes to an existing CRM, clienteling platform or collaboration tool.'], ['Can it understand jewelry materials and terminology?', 'It can be configured around company product information and vocabulary, but terminology, accents and scenario accuracy must be evaluated with representative samples.'], ['Will it reply to clients automatically?', 'The default is to create summaries, tasks and suggestions for advisor review. Further automation depends on channel rules, workflow boundaries and compliance.'], ['Has this been validated in jewelry sales?', 'We completed a paid, anonymized delivery for a high-end custom jewelry workflow using real enterprise-messaging sales records. Each new organization still requires its own evaluation.']],
      proofNote: 'TellWin has completed a paid delivery in an anonymized custom-jewelry scenario. This page does not disclose the client, operating data or unverified impact metrics; scope depends on data, compliance and pilot evaluation.',
    },
    ar: {
      kicker: 'الذكاء الاصطناعي لمبيعات المجوهرات',
      title: 'حوّل كل استشارة مجوهرات\nإلى معلومات عميل مستمرة.',
      intro: 'تساعد TellWin فرق المجوهرات الفاخرة ومجوهرات الزفاف والتصميم حسب الطلب على تنظيم الميزانية والمناسبة والطراز والمواد والمقاس والتفضيلات والمخاوف والالتزامات من الاستشارات والمحادثات الخاصة المصرح بها، كي يواصل المستشار الخدمة بسياق واضح ويدرّب المدير من تفاعلات فعلية.',
      primaryAction: 'ناقش تجربة لمبيعات المجوهرات', secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا تعتمد مبيعات المجوهرات على سياق كامل للعميل؟',
      problemsIntro: 'قد يمتد قرار المجوهرات عالية القيمة عبر استشارات وتجربة قطع ونقاشات عائلية وتعديلات في التصميم. ولا تحفظ بيانات الاتصال ودرجة الاهتمام التفضيلات الجمالية والغرض العاطفي وحدود الميزانية وتغير المخاوف.',
      problems: [['تظهر الاحتياجات عبر محادثات متعددة', 'تؤثر المناسبة والزفاف والاقتناء والهدايا في التصميم والمواد والميزانية والتوقيت، بينما تفصل الملاحظات المتناثرة بينها.'], ['يصعب تكرار الخدمة المتميزة', 'تبقى طريقة المستشار الخبير في اكتشاف الذوق وشرح الحرفية ومعالجة مخاوف السعر معرفة شخصية.'], ['يقطع التسليم استمرارية التجربة', 'عند تغير المناوبة أو المتجر يؤدي غياب التفضيلات والالتزامات إلى تكرار العميل لشرح احتياجاته وإضعاف الثقة.']],
      processTitle: 'أربع خطوات من الاستشارة إلى المتابعة المستمرة',
      processIntro: 'ابدأ بإشعار واضح وحدود للصلاحيات ومراجعة بشرية في متجر أو قناة واحدة، من دون اشتراط استبدال CRM أو نظام التجزئة الحالي.',
      process: [['01', 'ربط المحادثات المصرح بها', 'بعد تحديد الإشعار والغرض والاحتفاظ، اربط تسجيلات الاستشارة أو الرسائل الخاصة أو سجلات العمل المختارة.'], ['02', 'تنظيم التفضيلات والإشارات', 'حدد المناسبة والميزانية والطراز والمواد والمقاس والتوقيت والمشاركين في القرار والمخاوف والمنافسين وإشارات الشراء.'], ['03', 'إنشاء إجراءات متابعة للمستشار', 'أنشئ ملخصات قابلة للمراجعة وأسئلة مفتوحة والتزامات واقتراحات للخطوة التالية تحافظ على سياق العميل.'], ['04', 'بناء ذكاء خدمة للفريق', 'اكتشف الاحتياجات والاعتراضات وملاحظات المنتج وفرص التدريب المتكررة عبر المحادثات.']],
      valueTitle: 'سياق عميل واحد يربط المبيعات والتشغيل',
      value: [['مستشارو المجوهرات', 'استعادة التفضيلات والالتزامات بسرعة وتقليل تدوين الملاحظات والحفاظ على الاستمرارية.'], ['مديرو المتاجر والمبيعات', 'اكتشاف فرص التدريب وفجوات المتابعة والمشكلات المتكررة من محادثات فعلية.'], ['فرق المنتجات والعلامة', 'رؤية ملاحظات التصميم والمواد والمنتجات المتكررة ضمن حدود الخصوصية.']],
      fitTitle: 'أي فرق مجوهرات ينبغي أن تبدأ بالتجربة؟',
      fit: ['مبيعات المجوهرات الفاخرة أو مجوهرات الزفاف أو التصميم حسب الطلب', 'قرارات تتطلب استشارات وتجربة قطع أو تعديلات متعددة', 'وجود CRM مع بقاء سياق المحادثة في ملاحظات يدوية', 'الحاجة إلى أدلة تدريب محددة من خبرة كبار المستشارين', 'إمكانية إنشاء ضوابط للإشعار والصلاحيات والمراجعة البشرية'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات المجوهرات',
      faqs: [['هل TellWin نظام CRM لمتاجر المجوهرات؟', 'لا. تركز TellWin على فهم المحادثة ومعلومات العميل وتعيد النتائج المنظمة بعد مراجعتها إلى CRM أو منصة إدارة العملاء أو أداة التعاون الحالية.'], ['هل يفهم مواد المجوهرات ومصطلحاتها؟', 'يمكن إعداده وفق معلومات منتجات الشركة ومفرداتها، لكن يجب تقييم دقة المصطلحات واللهجات والسيناريوهات بعينات ممثلة.'], ['هل سيرد على العملاء تلقائياً؟', 'الوضع الافتراضي هو إنشاء ملخصات ومهام واقتراحات يراجعها المستشار. وتعتمد الأتمتة الإضافية على القناة وسير العمل والامتثال.'], ['هل جرى التحقق منه في مبيعات المجوهرات؟', 'أكملنا تنفيذاً مدفوعاً ومجهول الهوية لسير عمل مجوهرات فاخرة حسب الطلب باستخدام سجلات مبيعات فعلية من مراسلات المؤسسة، مع بقاء الحاجة إلى تقييم مستقل لكل مؤسسة.']],
      proofNote: 'أكملت TellWin تنفيذاً مدفوعاً في سيناريو مجوهرات حسب الطلب مجهول الهوية. لا تكشف الصفحة هوية العميل أو بيانات التشغيل أو مؤشرات أثر غير متحققة، ويعتمد النطاق على البيانات والامتثال وتقييم التجربة.',
    },
  },
  medicalDevice: {
    zh: {
      kicker: 'MEDICAL DEVICE SALES AI',
      title: '让专业销售沟通，\n成为可复核的客户与市场情报。',
      intro: 'TellWin 面向医疗器械与专业医疗产品销售团队，将获授权沟通中的客户角色、临床与业务需求、产品关注、异议、承诺事项和下一步整理为结构化上下文。它服务于销售跟进、团队辅导与市场反馈，不提供诊断或诊疗建议。',
      primaryAction: '讨论医疗器械销售试点', secondaryAction: '了解销售对话智能',
      problemsTitle: '为什么专业医疗销售不能只靠简单拜访记录？',
      problemsIntro: '医疗器械销售通常涉及临床、采购、设备、管理等多个角色，信息专业、决策周期长。只记录拜访次数和一句结果，无法解释不同角色真正关注什么。',
      problems: [['多角色需求容易混在一起', '临床使用、采购流程、预算、设备条件与管理要求来自不同角色，需要保留来源与语境。'], ['专业问题散落在个人记录里', '产品配置、使用场景、证据需求和未解决问题若未结构化，后续跟进与内部协同容易断层。'], ['主管难以获得具体辅导依据', '活动数量无法说明需求发现、问题回应和承诺管理的质量，抽查也难覆盖长周期沟通。']],
      processTitle: '从获授权沟通到可执行跟进的四个步骤',
      processIntro: '试点先明确数据边界、访问权限、保存周期与人工复核，并使用企业批准的产品资料和业务规则评估，不将模型输出当作医疗结论。',
      process: [['01', '确定合规与数据边界', '由企业确认可采集渠道、告知与授权、访问角色、保存周期，以及禁止进入系统的敏感信息。'], ['02', '整理角色与业务信号', '识别客户角色、需求、产品关注、异议、未决问题、竞品提及、承诺事项与时间计划。'], ['03', '生成可复核的跟进材料', '为销售形成摘要、待办和需内部确认的问题，由人员审核后进入 CRM 或现有协作流程。'], ['04', '汇总团队与市场反馈', '在权限和脱敏边界内观察重复问题、产品反馈与辅导机会，为业务复盘提供可追溯线索。']],
      valueTitle: '同一份专业语境，服务三个业务角色',
      value: [['一线销售', '快速恢复不同客户角色的关注点、承诺与下一步，减少重复整理。'], ['销售与区域主管', '基于实际沟通发现跟进断点和辅导机会，而不是只看活动数量。'], ['产品与市场团队', '在合规和脱敏边界内汇总反复出现的产品问题与市场反馈。']],
      fitTitle: '哪些团队适合先评估？',
      fit: ['医疗器械或专业医疗产品的长周期销售', '一次机会涉及多个业务与专业角色', '已有 CRM，但专业沟通仍依赖个人笔记', '能够提供企业批准的产品资料与评价标准', '能够建立授权、权限、脱敏和人工复核流程'],
      faqTitle: '医疗器械销售 AI 常见问题',
      faqs: [['TellWin 会提供医疗建议吗？', '不会。页面描述的是销售沟通整理与客户情报工作流，不用于诊断、治疗决策或替代医疗专业人员判断。'], ['能直接使用患者信息吗？', '不能默认这样做。试点必须由企业先定义允许的数据范围、授权依据、最小化采集、访问权限和脱敏要求。'], ['能理解专业产品术语吗？', '可基于企业批准的产品资料与词汇进行配置，但准确性必须用代表性样本和人工评测确认。'], ['是否已经在医疗器械行业规模化验证？', '当前页面描述目标工作流与计划评估，不宣称已完成该行业的规模化生产验证。']],
      proofNote: '本页描述 TellWin 在医疗器械销售场景的目标工作流和试点评估方法，不构成医疗、法律或合规建议，也不声称已完成该行业的规模化生产验证。',
    },
    en: {
      kicker: 'MEDICAL DEVICE SALES AI',
      title: 'Turn professional sales conversations\ninto reviewable customer and market intelligence.',
      intro: 'TellWin structures stakeholder roles, clinical and business needs, product questions, objections, commitments and next actions from approved conversations for medical device and professional healthcare-product sales teams. It supports follow-up, coaching and market feedback; it does not provide diagnosis or treatment advice.',
      primaryAction: 'Discuss a medical device sales pilot', secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why are simple visit notes insufficient for professional healthcare sales?',
      problemsIntro: 'Medical device decisions often involve clinical, procurement, equipment and management stakeholders over a long cycle. Visit counts and one-line outcomes cannot explain what each role actually needs.',
      problems: [['Stakeholder needs become mixed together', 'Clinical use, procurement, budget, equipment conditions and management requirements come from different roles and need source context.'], ['Professional questions remain in personal notes', 'Configuration, use-case, evidence and unresolved questions are difficult to hand off when they are not structured.'], ['Managers lack concrete coaching evidence', 'Activity volume does not show the quality of discovery, response or commitment management across a long sales cycle.']],
      processTitle: 'Four steps from approved conversation to actionable follow-up',
      processIntro: 'A pilot first defines data boundaries, access, retention and human review, then evaluates against company-approved product materials and business rules. Model output is not treated as a medical conclusion.',
      process: [['01', 'Define data and governance boundaries', 'The organization confirms allowed channels, notice and consent, access roles, retention and information that must remain outside the system.'], ['02', 'Structure stakeholders and business signals', 'Identify roles, needs, product questions, objections, open issues, competitor mentions, commitments and timing.'], ['03', 'Create reviewable follow-up material', 'Generate summaries, actions and questions requiring internal confirmation, reviewed before entering CRM or collaboration workflows.'], ['04', 'Aggregate team and market feedback', 'Within access and redaction controls, identify recurring questions, product feedback and coaching opportunities with traceable context.']],
      valueTitle: 'One professional context serving three business roles',
      value: [['Field sales', 'Recover stakeholder concerns, commitments and next actions quickly with less manual organization.'], ['Sales and regional managers', 'Find follow-up gaps and coaching opportunities in real interactions rather than activity counts alone.'], ['Product and marketing', 'Aggregate recurring product questions and market feedback within governance and redaction boundaries.']],
      fitTitle: 'Which teams should evaluate first?',
      fit: ['Long-cycle medical device or professional healthcare-product sales', 'Opportunities involve multiple professional and business stakeholders', 'CRM exists but professional context remains in personal notes', 'Company-approved product material and evaluation criteria are available', 'Notice, access, redaction and human-review controls can be established'],
      faqTitle: 'Medical device sales AI FAQ',
      faqs: [['Does TellWin provide medical advice?', 'No. This page describes a sales-conversation and customer-intelligence workflow, not diagnosis, treatment decisions or replacement of professional judgment.'], ['Can patient information be used directly?', 'Not by default. The organization must first define permitted data, authorization, data minimization, access and redaction requirements.'], ['Can it understand specialist product terminology?', 'It can be configured using company-approved materials and vocabulary, but accuracy must be validated with representative samples and human evaluation.'], ['Has this been validated at scale in medical devices?', 'This page describes a target workflow and planned evaluation; it does not claim scaled production validation in this industry.']],
      proofNote: 'This page describes a target workflow and pilot-evaluation method for medical device sales. It is not medical, legal or compliance advice and does not claim scaled production validation in this industry.',
    },
    ar: {
      kicker: 'الذكاء الاصطناعي لمبيعات الأجهزة الطبية',
      title: 'حوّل محادثات المبيعات المهنية\nإلى معلومات عملاء وسوق قابلة للمراجعة.',
      intro: 'تنظّم TellWin أدوار أصحاب المصلحة والاحتياجات السريرية والتجارية وأسئلة المنتج والاعتراضات والالتزامات والخطوات التالية من المحادثات المصرح بها لفرق مبيعات الأجهزة الطبية والمنتجات الصحية المهنية. وهي تدعم المتابعة والتدريب وملاحظات السوق ولا تقدم تشخيصاً أو نصيحة علاجية.',
      primaryAction: 'ناقش تجربة لمبيعات الأجهزة الطبية', secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا لا تكفي ملاحظات الزيارة البسيطة للمبيعات الصحية المهنية؟',
      problemsIntro: 'غالباً ما تشمل قرارات الأجهزة الطبية أطرافاً سريرية ومشتريات وتجهيزات وإدارة عبر دورة طويلة. ولا تفسر أعداد الزيارات والنتيجة المختصرة ما يحتاجه كل دور فعلياً.',
      problems: [['تختلط احتياجات أصحاب المصلحة', 'يأتي الاستخدام السريري والشراء والميزانية وظروف التجهيز ومتطلبات الإدارة من أدوار مختلفة ويجب الاحتفاظ بمصدرها وسياقها.'], ['تبقى الأسئلة المهنية في ملاحظات شخصية', 'يصعب تسليم معلومات التهيئة وحالة الاستخدام والأدلة والأسئلة المفتوحة عندما لا تكون منظمة.'], ['يفتقر المدير إلى دليل تدريب محدد', 'لا يوضح حجم النشاط جودة اكتشاف الاحتياجات والاستجابة وإدارة الالتزامات في دورة مبيعات طويلة.']],
      processTitle: 'أربع خطوات من المحادثة المصرح بها إلى المتابعة',
      processIntro: 'تحدد التجربة أولاً حدود البيانات والصلاحيات والاحتفاظ والمراجعة البشرية، ثم تقيّم باستخدام مواد المنتج وقواعد العمل المعتمدة من المؤسسة. ولا يُعامل خرج النموذج كاستنتاج طبي.',
      process: [['01', 'تحديد حدود البيانات والحوكمة', 'تؤكد المؤسسة القنوات المسموحة والإشعار والموافقة وأدوار الوصول والاحتفاظ والمعلومات التي يجب أن تبقى خارج النظام.'], ['02', 'تنظيم أصحاب المصلحة وإشارات العمل', 'تحديد الأدوار والاحتياجات وأسئلة المنتج والاعتراضات والمسائل المفتوحة والمنافسين والالتزامات والتوقيت.'], ['03', 'إنشاء مواد متابعة قابلة للمراجعة', 'إنتاج ملخصات وإجراءات وأسئلة تحتاج إلى تأكيد داخلي، ومراجعتها قبل إدخالها في CRM أو أدوات التعاون.'], ['04', 'تجميع ملاحظات الفريق والسوق', 'ضمن ضوابط الصلاحيات وإخفاء الهوية، اكتشاف الأسئلة وملاحظات المنتج وفرص التدريب المتكررة بسياق قابل للتتبع.']],
      valueTitle: 'سياق مهني واحد يخدم ثلاثة أدوار تجارية',
      value: [['المبيعات الميدانية', 'استعادة اهتمامات أصحاب المصلحة والالتزامات والخطوات التالية بسرعة مع تقليل التنظيم اليدوي.'], ['مديرو المبيعات والمناطق', 'اكتشاف فجوات المتابعة وفرص التدريب من التفاعلات الفعلية لا من أعداد النشاط فقط.'], ['فرق المنتج والتسويق', 'تجميع أسئلة المنتج وملاحظات السوق المتكررة ضمن حدود الحوكمة وإخفاء الهوية.']],
      fitTitle: 'أي فرق ينبغي أن تبدأ بالتقييم؟',
      fit: ['مبيعات الأجهزة الطبية أو المنتجات الصحية المهنية طويلة الدورة', 'الفرصة تشمل أطرافاً مهنية وتجارية متعددة', 'وجود CRM مع بقاء السياق المهني في ملاحظات شخصية', 'توفر مواد منتج ومعايير تقييم معتمدة من المؤسسة', 'إمكانية إنشاء ضوابط للإشعار والصلاحيات وإخفاء الهوية والمراجعة البشرية'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات الأجهزة الطبية',
      faqs: [['هل تقدم TellWin نصيحة طبية؟', 'لا. تصف الصفحة سير عمل لمحادثات المبيعات ومعلومات العملاء، وليس التشخيص أو قرارات العلاج أو استبدال الحكم المهني.'], ['هل يمكن استخدام معلومات المرضى مباشرة؟', 'ليس افتراضياً. يجب على المؤسسة أولاً تحديد البيانات المسموحة وأساس التفويض وتقليل البيانات والصلاحيات ومتطلبات إخفاء الهوية.'], ['هل يفهم مصطلحات المنتج المتخصصة؟', 'يمكن إعداده بمواد ومفردات معتمدة من المؤسسة، لكن يجب التحقق من الدقة بعينات ممثلة وتقييم بشري.'], ['هل تم التحقق منه على نطاق واسع في الأجهزة الطبية؟', 'تصف الصفحة سير عمل مستهدفاً وتقييماً مخططاً، ولا تدعي تحققاً إنتاجياً واسع النطاق في هذا القطاع.']],
      proofNote: 'تصف هذه الصفحة سير عمل مستهدفاً وطريقة تقييم تجربة لمبيعات الأجهزة الطبية. ولا تمثل نصيحة طبية أو قانونية أو امتثالاً، ولا تدعي تحققاً إنتاجياً واسع النطاق في هذا القطاع.',
    },
  },
  realEstate: {
    zh: {
      kicker: 'REAL ESTATE SALES AI',
      title: '让每一次房产顾问沟通，\n都沉淀为可跟进的客户情报。',
      intro: 'TellWin 面向迪拜及其他高价值房地产销售团队，将电话、面谈和私域沟通中的预算、区域偏好、户型需求、购买动机、决策人和下一步整理为统一客户上下文，帮助顾问跟进，也帮助管理者看见真实销售现场。',
      primaryAction: '讨论房地产销售试点',
      secondaryAction: '了解销售对话智能',
      problemsTitle: '房地产销售为什么容易丢失客户语境？',
      problemsIntro: '客户可能跨时区、跨语言、跨渠道比较多个项目。线索数量不等于有效跟进；决定转化质量的，往往是团队能否完整理解并接续每一次沟通。',
      problems: [
        ['客户需求分散在不同渠道', '电话、WhatsApp、面谈和 CRM 备注彼此割裂，顾问很难快速恢复完整上下文。'],
        ['管理者只看到结果和活动量', '通话次数和跟进状态无法说明顾问是否识别预算、决策角色、真实顾虑与购买时点。'],
        ['跨语言团队难以统一服务标准', '英文、阿语与其他语言沟通并存，客户表达和优秀顾问方法难以系统沉淀。'],
      ],
      processTitle: '为房地产销售设计的客户情报流程',
      processIntro: '先从一个团队、一个渠道和一组可衡量的跟进目标开始，不要求企业先替换 CRM。',
      process: [
        ['01', '采集获准的客户沟通', '连接选定的电话、面谈或私域入口，并明确当地法规、公司政策和客户告知要求。'],
        ['02', '生成房产客户档案', '识别预算、用途、自住或投资偏好、区域、户型、付款计划、决策人、顾虑和时间线。'],
        ['03', '辅助顾问及时跟进', '输出沟通摘要、待办、未回答问题和下一步建议，减少交接与重复询问。'],
        ['04', '让管理者看见共性', '发现反复出现的项目反馈、流失原因、团队辅导重点与市场问题。'],
      ],
      valueTitle: '从单次跟进到团队级增长能力',
      value: [
        ['经纪人和置业顾问', '快速恢复客户上下文，减少整理时间，让后续沟通更连续。'],
        ['销售经理', '基于真实沟通做辅导，识别线索质量、跟进缺口和团队共性。'],
        ['开发商与项目团队', '汇总客户对区域、户型、价格、付款方式和竞品项目的真实反馈。'],
      ],
      fitTitle: '适合哪些房地产团队？',
      fit: ['服务国际客户的迪拜经纪公司', '拥有多项目、多语言顾问团队的开发商', '高端住宅、投资物业与长周期客户', '已经使用 CRM，但沟通上下文仍依赖个人', '希望先以小范围真实数据验证 AI 销售能力'],
      faqTitle: '房地产销售 AI 常见问题',
      faqs: [
        ['TellWin 是房地产 CRM 吗？', '不是。TellWin 聚焦客户对话理解与销售情报，可与现有 CRM 配合，将更完整的沟通上下文写回客户记录。'],
        ['支持英文和阿语沟通吗？', '产品方向覆盖多语言沟通，但具体语言、口音与业务词汇需要在试点中用真实样本评测后确认。'],
        ['能否直接给客户发送回复？', '默认先生成摘要、待办和建议，由顾问确认后行动；是否自动发送取决于渠道能力、业务规则与合规边界。'],
        ['如何开始迪拜市场试点？', '选择一个销售团队、一类客户和一个沟通入口，明确数据与合规边界，再用真实跟进任务验证准确性和采用情况。'],
      ],
      proofNote: '迪拜房地产页面描述目标场景与实施方式，不代表已在所有语言、渠道或当地系统完成标准化接入。具体能力以试点评测和合规确认结果为准。',
    },
    en: {
      kicker: 'AI SALES COPILOT FOR DUBAI REAL ESTATE',
      title: 'Turn every property conversation\ninto customer intelligence your team can act on.',
      intro: 'TellWin helps high-value real estate sales teams in Dubai and similar markets structure budget, location preferences, property requirements, buyer motivation, decision roles and next actions from calls, meetings and private messaging—giving advisors continuity and managers a clearer view of real sales conversations.',
      primaryAction: 'Discuss a real estate pilot',
      secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why do real estate teams lose customer context?',
      problemsIntro: 'Buyers compare projects across time zones, languages and channels. Lead volume alone does not create effective follow-up; conversion quality depends on whether the team can understand and continue every important conversation.',
      problems: [
        ['Buyer needs are scattered across channels', 'Calls, WhatsApp, meetings and CRM notes remain disconnected, making full context difficult to recover.'],
        ['Managers see activity, not conversation quality', 'Call counts and statuses do not show whether an advisor understood budget, decision roles, concerns and purchase timing.'],
        ['Multilingual teams struggle to standardize service', 'English, Arabic and other languages coexist, while customer language and top-advisor methods remain difficult to retain.'],
      ],
      processTitle: 'A customer intelligence workflow for property sales',
      processIntro: 'Start with one team, one communication source and measurable follow-up goals. There is no requirement to replace the CRM first.',
      process: [
        ['01', 'Capture approved conversations', 'Connect selected calls, meetings or private channels with clear local legal, company policy and customer notice requirements.'],
        ['02', 'Build the property buyer profile', 'Identify budget, use case, investment or end-user intent, location, unit type, payment plan, decision roles, concerns and timing.'],
        ['03', 'Help advisors follow up', 'Produce summaries, actions, unanswered questions and next-step guidance to reduce handoff gaps and repeated questions.'],
        ['04', 'Show managers the patterns', 'Surface recurring project feedback, loss reasons, coaching priorities and market questions across conversations.'],
      ],
      valueTitle: 'From individual follow-up to a team growth capability',
      value: [
        ['Property advisors', 'Recover buyer context quickly, spend less time organizing notes and maintain continuity.'],
        ['Sales managers', 'Coach from real conversations and identify lead-quality, follow-up and team-wide gaps.'],
        ['Developers and project teams', 'Aggregate direct feedback about locations, units, pricing, payment plans and competing projects.'],
      ],
      fitTitle: 'Who is this designed for?',
      fit: ['Dubai brokerages serving international buyers', 'Developers with multilingual, multi-project sales teams', 'Luxury residential and investment-property sales', 'Teams with CRM but conversation context still owned by individuals', 'Organizations that want a focused real-data AI pilot first'],
      faqTitle: 'Dubai real estate sales AI FAQ',
      faqs: [
        ['Is TellWin a real estate CRM?', 'No. TellWin focuses on conversation understanding and sales intelligence, complementing the CRM by returning richer customer context to existing records.'],
        ['Does it support English and Arabic?', 'The product direction covers multilingual conversations, but each language, accent and property vocabulary must be evaluated with representative pilot samples.'],
        ['Can it automatically message buyers?', 'The default approach produces summaries, actions and suggestions for advisor review. Automation depends on channel capability, business rules and compliance boundaries.'],
        ['How would a Dubai pilot start?', 'Choose one sales team, buyer segment and communication source; define data and compliance boundaries; then evaluate accuracy and adoption using real follow-up work.'],
      ],
      proofNote: 'This page describes the target workflow and implementation approach. It does not claim standardized integration across every language, channel or local system. Final scope depends on pilot evaluation and compliance review.',
    },
    ar: {
      kicker: 'مساعد مبيعات ذكي لعقارات دبي',
      title: 'حوّل كل محادثة عقارية\nإلى معلومات عملاء يستطيع فريقك تنفيذها.',
      intro: 'تساعد TellWin فرق مبيعات العقارات عالية القيمة في دبي والأسواق المشابهة على تنظيم الميزانية والمناطق المفضلة ومتطلبات العقار ودافع الشراء وأصحاب القرار والخطوات التالية من المكالمات والاجتماعات والرسائل الخاصة، لتمنح المستشار استمرارية والمدير رؤية أوضح للمبيعات الفعلية.',
      primaryAction: 'ناقش تجربة لفريق عقاري',
      secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا تفقد فرق العقارات سياق العميل؟',
      problemsIntro: 'يقارن المشترون المشاريع عبر مناطق زمنية ولغات وقنوات متعددة. كثرة العملاء المحتملين لا تضمن المتابعة؛ فجودة التحويل تعتمد على قدرة الفريق على فهم كل محادثة مهمة ومواصلتها.',
      problems: [
        ['احتياجات المشتري موزعة بين القنوات', 'تبقى المكالمات وWhatsApp والاجتماعات وملاحظات CRM منفصلة، فيصعب استعادة السياق الكامل.'],
        ['يرى المدير النشاط ولا يرى جودة الحوار', 'لا توضح أعداد المكالمات والحالات ما إذا فهم المستشار الميزانية وأصحاب القرار والمخاوف وموعد الشراء.'],
        ['يصعب توحيد الخدمة في الفرق متعددة اللغات', 'تتعايش العربية والإنجليزية ولغات أخرى، بينما يصعب الاحتفاظ بلغة العملاء وأساليب أفضل المستشارين.'],
      ],
      processTitle: 'سير معلومات عملاء مصمم للمبيعات العقارية',
      processIntro: 'ابدأ بفريق واحد ومصدر تواصل واحد وأهداف متابعة قابلة للقياس، من دون اشتراط استبدال CRM أولاً.',
      process: [
        ['01', 'جمع المحادثات المصرح بها', 'ربط المكالمات أو الاجتماعات أو القنوات المختارة مع مراعاة القانون المحلي وسياسة الشركة وإشعار العميل.'],
        ['02', 'إنشاء ملف مشتري العقار', 'تحديد الميزانية والغرض والاستثمار أو السكن والمنطقة ونوع الوحدة وخطة الدفع وأصحاب القرار والمخاوف والتوقيت.'],
        ['03', 'مساعدة المستشار على المتابعة', 'إنتاج ملخصات ومهام وأسئلة غير مجابة واقتراح الخطوة التالية لتقليل فجوات التسليم وتكرار الأسئلة.'],
        ['04', 'إظهار الأنماط للإدارة', 'اكتشاف ملاحظات المشاريع وأسباب الخسارة وأولويات التدريب وأسئلة السوق المتكررة.'],
      ],
      valueTitle: 'من متابعة فردية إلى قدرة نمو للفريق',
      value: [
        ['المستشارون العقاريون', 'استعادة سياق المشتري بسرعة وتقليل وقت الملاحظات والحفاظ على استمرارية الحوار.'],
        ['مديرو المبيعات', 'التدريب من محادثات فعلية واكتشاف فجوات جودة العملاء والمتابعة والفريق.'],
        ['المطورون وفرق المشاريع', 'تجميع ملاحظات مباشرة حول المناطق والوحدات والأسعار وخطط الدفع والمشاريع المنافسة.'],
      ],
      fitTitle: 'لمن صُمم هذا الحل؟',
      fit: ['شركات الوساطة في دبي التي تخدم مشترين دوليين', 'المطورون ذوو فرق مبيعات متعددة المشاريع واللغات', 'مبيعات المساكن الفاخرة والعقارات الاستثمارية', 'فرق تستخدم CRM لكن سياق المحادثة ما زال لدى الأفراد', 'مؤسسات تريد تجربة ذكاء اصطناعي محددة ببيانات فعلية'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات عقارات دبي',
      faqs: [
        ['هل TellWin نظام CRM عقاري؟', 'لا. تركز TellWin على فهم المحادثة وذكاء المبيعات، وتكمل CRM بإعادة سياق أغنى إلى سجل العميل.'],
        ['هل يدعم العربية والإنجليزية؟', 'يشمل اتجاه المنتج المحادثات متعددة اللغات، لكن يجب تقييم كل لغة ولهجة ومفردات عقارية بعينات ممثلة في التجربة.'],
        ['هل يمكنه إرسال رسائل للمشترين تلقائياً؟', 'ينتج النهج الافتراضي ملخصات ومهام واقتراحات يراجعها المستشار. وتعتمد الأتمتة على القناة وقواعد العمل وحدود الامتثال.'],
        ['كيف تبدأ تجربة في دبي؟', 'اختر فريق مبيعات وشريحة مشترين ومصدر تواصل واحداً، وحدد حدود البيانات والامتثال، ثم قيّم الدقة والاستخدام بمهام متابعة فعلية.'],
      ],
      proofNote: 'تصف هذه الصفحة سير العمل المستهدف ونهج التنفيذ ولا تدّعي تكاملاً موحداً مع كل لغة أو قناة أو نظام محلي. يعتمد النطاق النهائي على تقييم التجربة ومراجعة الامتثال.',
    },
  },
}

export const seoLandingUi = {
  zh: {
    businessGap: '业务断点',
    conversationToAction: '从对话到行动',
    whoGetsValue: '价值角色',
    rightTeam: '从合适团队开始',
    related: '相关 TellWin 页面',
    tellwinLink: 'TellWin AI 销售副驾 →',
    fdeLink: 'FDE 企业 AI 落地服务 →',
    salesIntelligenceLink: '销售情报与对话智能 →',
    realEstateLink: '房地产销售 AI →',
    salesCallLink: 'AI 销售通话分析 →',
    automotiveLink: '汽车销售 AI →',
    jewelryLink: '珠宝销售 AI →',
    medicalDeviceLink: '医疗器械销售 AI →',
    dubaiSource: '迪拜土地局市场资料 ↗',
  },
  en: {
    businessGap: 'THE BUSINESS GAP',
    conversationToAction: 'FROM CONVERSATION TO ACTION',
    whoGetsValue: 'WHO GETS VALUE',
    rightTeam: 'START WITH THE RIGHT TEAM',
    related: 'Related TellWin pages',
    tellwinLink: 'TellWin AI Sales Copilot →',
    fdeLink: 'FDE Enterprise AI Delivery →',
    salesIntelligenceLink: 'Sales Intelligence from Conversations →',
    realEstateLink: 'Real Estate Sales AI →',
    salesCallLink: 'AI Sales Call Analysis →',
    automotiveLink: 'Automotive Sales AI →',
    jewelryLink: 'Jewelry Sales AI →',
    medicalDeviceLink: 'Medical Device Sales AI →',
    dubaiSource: 'Dubai Land Department market reference ↗',
  },
  ar: {
    businessGap: 'فجوة العمل',
    conversationToAction: 'من المحادثة إلى الإجراء',
    whoGetsValue: 'من يستفيد',
    rightTeam: 'ابدأ بالفريق المناسب',
    related: 'صفحات TellWin ذات صلة',
    tellwinLink: 'مساعد مبيعات TellWin بالذكاء الاصطناعي ←',
    fdeLink: 'تنفيذ الذكاء الاصطناعي للمؤسسات FDE ←',
    salesIntelligenceLink: 'ذكاء المبيعات من المحادثات ←',
    realEstateLink: 'الذكاء الاصطناعي لمبيعات العقارات ←',
    salesCallLink: 'تحليل مكالمات المبيعات بالذكاء الاصطناعي ←',
    automotiveLink: 'الذكاء الاصطناعي لمبيعات السيارات ←',
    jewelryLink: 'الذكاء الاصطناعي لمبيعات المجوهرات ←',
    medicalDeviceLink: 'الذكاء الاصطناعي لمبيعات الأجهزة الطبية ←',
    dubaiSource: 'مرجع سوق دائرة الأراضي والأملاك في دبي ↗',
  },
}
