export const seoLandingContent = {
  salesIntelligence: {
    zh: {
      kicker: 'SALES CONVERSATION INTELLIGENCE',
      title: '让销售对话不再散落，\n而是成为可行动的客户情报。',
      intro: 'TellWin 将面对面沟通、企业微信等渠道里的客户对话，整理为结构化客户档案、购买信号、异议、待办和跨团队洞察。它不是只做录音转写，而是让销售现场持续进入企业的跟进、辅导与经营决策。',
      primaryAction: '预约销售场景诊断',
      secondaryAction: '查看 TellWin 产品',
      problemsTitle: '为什么企业需要销售对话分析，而不只是 CRM？',
      problemsIntro: 'CRM 记录结果，客户对话解释结果。没有完整语境，管理者只能看到跟进状态，却很难知道客户为什么犹豫、销售哪里需要帮助、产品问题正在怎样重复出现。',
      problems: [
        ['客户信息依赖手工填写', '销售结束沟通后再补录，容易遗漏预算、决策人、竞品、真实异议和承诺事项。'],
        ['优秀经验留在少数人身上', '高绩效销售的提问、倾听和异议处理难以被团队看见，新人辅导只能依赖抽象复盘。'],
        ['客户原声到不了决策层', '一线需求经过多次转述，产品、市场和管理层看到的是结论，而不是可以核验的客户语境。'],
      ],
      processTitle: '从对话到行动的四个步骤',
      processIntro: '每一步都保留原始语境和人工确认边界，让 AI 提高整理与发现效率，不替代销售和管理者作最终判断。',
      process: [
        ['01', '连接沟通入口', '在获得授权并明确数据边界的前提下，接入面对面录音、企业微信或现有业务系统。'],
        ['02', '识别关键信息', '提取客户诉求、预算、角色、时间计划、购买信号、异议、竞品提及和跟进事项。'],
        ['03', '进入业务动作', '为销售生成摘要和下一步，为主管形成辅导线索，并把结构化结果写入 CRM 或飞书。'],
        ['04', '形成组织洞察', '跨对话观察需求、流失原因、话术表现和产品反馈，让客户原声进入经营复盘。'],
      ],
      valueTitle: '同一份客户情报，服务三个角色',
      value: [
        ['一线销售', '减少整理时间，快速回顾客户上下文、承诺与下一步。'],
        ['销售主管', '从真实对话定位团队共性问题，让辅导有具体依据。'],
        ['产品与市场', '持续看见客户需求、竞品比较和反复出现的反馈。'],
      ],
      fitTitle: '什么团队最适合先做试点？',
      fit: ['客单价高、成交依赖深度沟通', '销售周期长、多人参与决策', '客户资产容易随人员流动', '已有 CRM，但一线记录质量不稳定', '希望从真实数据开始验证 AI，而不是先换整套系统'],
      faqTitle: '销售对话智能常见问题',
      faqs: [
        ['它和录音转写工具有什么区别？', '转写解决“说了什么”，TellWin 进一步识别客户状态、业务信号、行动事项与跨对话趋势，并把结果接回销售流程。'],
        ['必须替换现有 CRM 吗？', '不需要。可以先从一个团队或一种沟通入口开始，将结果写回现有 CRM、飞书多维表格或其他业务系统。'],
        ['如何处理隐私与授权？', '试点前会明确采集告知、数据用途、权限、保存周期与脱敏要求；敏感行业可进一步讨论私有化和区域化部署。'],
        ['多久能判断是否值得继续？', '先选一个业务目标明确、数据可获得的小范围场景，用真实使用和评测结果决定是否扩展，不预设统一周期。'],
      ],
      proofNote: '页面描述为 TellWin 当前可公开的产品能力与实施方法。实际接入范围和效果取决于数据基础、合规要求与团队使用方式。',
    },
    en: {
      kicker: 'SALES CONVERSATION INTELLIGENCE',
      title: 'Turn scattered sales conversations\ninto actionable customer intelligence.',
      intro: 'TellWin structures customer conversations from in-person meetings, private messaging and existing business systems into customer records, buying signals, objections, follow-ups and cross-team insight. It goes beyond transcription so the reality of sales can inform execution, coaching and management decisions.',
      primaryAction: 'Book a sales workflow diagnosis',
      secondaryAction: 'Explore TellWin',
      problemsTitle: 'Why conversation intelligence—not CRM alone?',
      problemsIntro: 'CRM records outcomes; conversations explain them. Without the customer context, leaders can see pipeline status but not why a buyer hesitates, where a salesperson needs support or which product issue keeps recurring.',
      problems: [
        ['Critical context depends on manual entry', 'Post-call updates often miss budget, decision roles, competitors, real objections and commitments.'],
        ['Winning behavior stays with a few people', 'The questions, listening and objection handling of top performers remain hard to observe and difficult to teach.'],
        ['Customer voice never reaches decision-makers', 'After repeated retelling, product and marketing teams receive conclusions without the original, verifiable context.'],
      ],
      processTitle: 'Four steps from conversation to action',
      processIntro: 'Each step preserves source context and human review. AI accelerates organization and discovery; salespeople and leaders retain the final judgment.',
      process: [
        ['01', 'Connect communication sources', 'With clear consent and data boundaries, connect in-person recordings, private messaging or existing business systems.'],
        ['02', 'Identify business signals', 'Extract needs, budget, stakeholders, timing, buying signals, objections, competitor mentions and follow-up actions.'],
        ['03', 'Return insight to the workflow', 'Give salespeople summaries, managers coaching evidence, and write structured outcomes into CRM or collaboration tools.'],
        ['04', 'Build organizational intelligence', 'Analyze recurring needs, loss reasons, sales behavior and product feedback across conversations.'],
      ],
      valueTitle: 'One customer intelligence asset, three teams',
      value: [
        ['Sales representatives', 'Spend less time organizing notes and recover customer context, commitments and next actions quickly.'],
        ['Sales managers', 'Coach from real conversations and identify recurring team-level gaps.'],
        ['Product and marketing', 'Continuously see customer needs, competitor comparisons and repeated feedback.'],
      ],
      fitTitle: 'Which teams should pilot first?',
      fit: ['High-value purchases depend on consultative conversations', 'Long sales cycles involve several decision-makers', 'Customer relationships are vulnerable to staff turnover', 'A CRM exists, but frontline data quality is inconsistent', 'The team wants to validate AI with real data before replacing core systems'],
      faqTitle: 'Sales conversation intelligence FAQ',
      faqs: [
        ['How is this different from transcription?', 'Transcription captures what was said. TellWin identifies customer state, business signals, actions and cross-conversation patterns, then returns them to the sales workflow.'],
        ['Do we need to replace our CRM?', 'No. A pilot can start with one team or communication source and write structured results into the CRM or collaboration system you already use.'],
        ['How do you handle privacy and consent?', 'Before a pilot, we define notice and consent, purpose, access, retention and redaction. Private or regional deployment can be assessed for sensitive environments.'],
        ['How quickly can we evaluate a pilot?', 'Start with one measurable workflow and real data, then decide whether to expand from observed adoption and evaluation results rather than a fixed promise.'],
      ],
      proofNote: 'This page describes currently public TellWin capabilities and implementation methods. Integration scope and outcomes depend on data readiness, compliance requirements and team adoption.',
    },
    ar: {
      kicker: 'ذكاء محادثات المبيعات',
      title: 'حوّل محادثات المبيعات المتفرقة\nإلى معلومات عملاء قابلة للتنفيذ.',
      intro: 'تنظّم TellWin محادثات العملاء من اللقاءات المباشرة والرسائل الخاصة والأنظمة الحالية إلى ملفات عملاء وإشارات شراء واعتراضات ومهام متابعة ورؤى مشتركة. وهي تتجاوز النسخ النصي لتربط واقع المبيعات بالتنفيذ والتدريب والقرارات الإدارية.',
      primaryAction: 'احجز تشخيصاً لسير المبيعات',
      secondaryAction: 'استكشف TellWin',
      problemsTitle: 'لماذا تحتاج المؤسسة إلى ذكاء المحادثات إلى جانب CRM؟',
      problemsIntro: 'يسجل CRM النتائج، بينما تفسر المحادثات أسبابها. ومن دون سياق العميل يرى القادة حالة الفرص ولا يعرفون سبب التردد أو موضع حاجة البائع للدعم أو المشكلة المتكررة في المنتج.',
      problems: [
        ['السياق المهم يعتمد على الإدخال اليدوي', 'غالباً ما تفقد التحديثات اللاحقة الميزانية وأصحاب القرار والمنافسين والاعتراضات والالتزامات.'],
        ['خبرة الأداء العالي تبقى لدى أفراد محدودين', 'يصعب ملاحظة أسئلة أفضل البائعين وطريقة استماعهم ومعالجة الاعتراضات وتحويلها إلى تدريب للفريق.'],
        ['صوت العميل لا يصل إلى صانع القرار', 'بعد تكرار نقل المعلومات تصل إلى فرق المنتج والتسويق استنتاجات من دون السياق الأصلي القابل للتحقق.'],
      ],
      processTitle: 'أربع خطوات من المحادثة إلى الإجراء',
      processIntro: 'تحافظ كل خطوة على المصدر والمراجعة البشرية. يسرّع الذكاء الاصطناعي التنظيم والاكتشاف، بينما يبقى القرار النهائي لدى الفريق.',
      process: [
        ['01', 'ربط مصادر التواصل', 'بعد توضيح الموافقة وحدود البيانات، تُربط التسجيلات الميدانية والرسائل الخاصة أو أنظمة العمل الحالية.'],
        ['02', 'اكتشاف إشارات العمل', 'استخراج الاحتياجات والميزانية والأدوار والتوقيت وإشارات الشراء والاعتراضات والمنافسين وخطوات المتابعة.'],
        ['03', 'إعادة الرؤية إلى سير العمل', 'تقديم ملخصات للبائع وأدلة تدريب للمدير وكتابة النتائج المنظمة في CRM أو أدوات التعاون.'],
        ['04', 'بناء معرفة مؤسسية', 'تحليل الاحتياجات المتكررة وأسباب الخسارة وسلوك المبيعات وملاحظات المنتج عبر المحادثات.'],
      ],
      valueTitle: 'أصل واحد لمعلومات العملاء يخدم ثلاثة فرق',
      value: [
        ['فريق المبيعات', 'تقليل وقت تنظيم الملاحظات واستعادة سياق العميل والالتزامات والخطوة التالية بسرعة.'],
        ['مديرو المبيعات', 'التدريب انطلاقاً من محادثات فعلية واكتشاف الفجوات المشتركة في الفريق.'],
        ['المنتج والتسويق', 'رؤية مستمرة لاحتياجات العملاء ومقارنات المنافسين والملاحظات المتكررة.'],
      ],
      fitTitle: 'من الأنسب لبدء تجربة أولى؟',
      fit: ['عمليات شراء عالية القيمة تعتمد على الحوار الاستشاري', 'دورة مبيعات طويلة تضم عدة أصحاب قرار', 'علاقات العملاء معرضة للتأثر بتغير الموظفين', 'وجود CRM مع تفاوت جودة بيانات الخط الأمامي', 'الرغبة في اختبار الذكاء الاصطناعي ببيانات فعلية قبل استبدال الأنظمة الأساسية'],
      faqTitle: 'أسئلة شائعة حول ذكاء محادثات المبيعات',
      faqs: [
        ['ما الفرق بينه وبين النسخ النصي؟', 'النسخ يسجل ما قيل، بينما تحدد TellWin حالة العميل وإشارات العمل والإجراءات والأنماط عبر المحادثات ثم تعيدها إلى سير المبيعات.'],
        ['هل يجب استبدال CRM الحالي؟', 'لا. يمكن أن تبدأ التجربة بفريق أو مصدر تواصل واحد وكتابة النتائج المنظمة في النظام المستخدم حالياً.'],
        ['كيف تتعاملون مع الخصوصية والموافقة؟', 'قبل التجربة نحدد الإشعار والموافقة والغرض والصلاحيات ومدة الاحتفاظ وإخفاء البيانات، مع تقييم النشر الخاص أو الإقليمي عند الحاجة.'],
        ['متى يمكن تقييم التجربة؟', 'نبدأ بسير عمل قابل للقياس وبيانات فعلية، ثم نقرر التوسع بناءً على الاستخدام ونتائج التقييم بدلاً من وعد زمني ثابت.'],
      ],
      proofNote: 'تعرض هذه الصفحة قدرات TellWin وأساليب التنفيذ المتاحة للنشر حالياً. يعتمد نطاق الربط والنتائج على جاهزية البيانات ومتطلبات الامتثال وتبنّي الفريق.',
    },
  },
  salesCallAnalysis: {
    zh: {
      kicker: 'AI SALES CALL ANALYSIS',
      title: '不只转写销售通话，\n还要看懂客户为什么买、为什么犹豫。',
      intro: 'TellWin 将获得授权的销售电话与面对面沟通整理为客户需求、购买信号、异议、竞品提及、承诺事项和下一步，让销售快速跟进，也让主管基于真实语境进行辅导。',
      primaryAction: '讨论销售通话分析试点',
      secondaryAction: '了解 TellWin 产品',
      problemsTitle: '为什么通话录音很多，团队仍然缺少销售洞察？',
      problemsIntro: '录音解决了“有没有留下”，但没有自动解决“谁来听、看什么、如何行动”。如果信息仍靠人工回忆和抽查，关键客户语境依然很难进入销售流程。',
      problems: [
        ['录音难以逐条复听', '主管不可能完整听完所有通话，抽查又容易错过真正需要辅导或及时跟进的对话。'],
        ['摘要缺少业务结构', '通用摘要往往没有区分预算、决策人、购买时点、异议、竞品和承诺事项。'],
        ['分析结果没有进入动作', '即使得到纪要，如果没有进入 CRM、待办和主管复盘，洞察仍停留在一个孤立工具里。'],
      ],
      processTitle: '从一段销售通话到可执行跟进',
      processIntro: '围绕真实销售流程配置字段和评测标准，并保留原始语境与人工确认，不让模型输出直接替代业务判断。',
      process: [
        ['01', '接入获准的通话', '明确客户告知、使用目的、访问权限和保存周期后，连接选定录音或沟通入口。'],
        ['02', '提取销售关键信号', '识别客户诉求、预算、角色、购买时点、异议、竞品、承诺和未回答问题。'],
        ['03', '生成角色化结果', '为销售输出摘要与待办，为主管提供辅导线索，为管理层形成可追溯的趋势视图。'],
        ['04', '回写现有工作流', '将经确认的结构化结果接入 CRM、飞书或团队当前使用的跟进系统。'],
      ],
      valueTitle: '一段通话，形成三种业务价值',
      value: [
        ['销售跟进', '快速恢复客户上下文，明确承诺事项、未回答问题和下一次触达重点。'],
        ['主管辅导', '定位提问、倾听、需求确认和异议处理中的具体片段，而不是只看结果。'],
        ['经营洞察', '跨通话观察客户需求、流失原因、竞品提及和产品反馈的重复模式。'],
      ],
      fitTitle: '哪些通话场景值得先分析？',
      fit: ['客单价高、一次通话包含大量决策信息', '销售周期长、需要多次接续沟通', '主管抽听成本高、辅导缺少依据', '已有录音，但尚未形成结构化客户档案', '能够取得合法授权并明确数据使用边界'],
      faqTitle: 'AI 销售通话分析常见问题',
      faqs: [
        ['它和通话转写有什么区别？', '转写主要回答“说了什么”；TellWin 进一步按销售场景识别客户状态、异议、承诺、下一步和跨通话趋势。'],
        ['会自动给销售打分吗？', '可以围绕企业确认的标准形成评测线索，但不建议用未经校准的模型分数直接替代主管判断或作为单一绩效依据。'],
        ['能接入现有 CRM 吗？', '可以先验证字段、准确性和使用方式，再根据现有系统接口确定回写范围，不要求先替换 CRM。'],
        ['如何保护客户隐私？', '试点前应明确告知与授权、用途、权限、保存和删除规则；实际方案需要结合当地法规与企业制度确认。'],
      ],
      proofNote: '本页描述 TellWin 的目标工作流与公开能力。具体通话来源、识别准确性、系统接入和合规方式须通过真实样本评测与实施确认。',
    },
    en: {
      kicker: 'AI SALES CALL ANALYSIS',
      title: 'Go beyond sales call transcripts\nto understand why buyers act—or hesitate.',
      intro: 'TellWin structures approved sales calls and in-person conversations into needs, buying signals, objections, competitor mentions, commitments and next actions—helping representatives follow up and managers coach from real context.',
      primaryAction: 'Discuss a call analysis pilot',
      secondaryAction: 'Explore TellWin',
      problemsTitle: 'Why do recorded calls still fail to produce sales insight?',
      problemsIntro: 'Recording answers whether the conversation was retained, but not who will review it, what matters or what happens next. Manual recall and occasional sampling still leave important customer context outside the workflow.',
      problems: [
        ['Teams cannot replay every call', 'Managers cannot listen to everything, while random sampling can miss the conversations that need urgent follow-up or coaching.'],
        ['Generic summaries lack sales structure', 'A general recap may not distinguish budget, decision roles, purchase timing, objections, competitors and commitments.'],
        ['Analysis remains disconnected from action', 'Even a useful summary creates little value when it does not reach CRM records, tasks or manager reviews.'],
      ],
      processTitle: 'From one sales call to an actionable follow-up',
      processIntro: 'Configure fields and evaluation criteria around the real workflow, preserve source context and human review, and never let model output replace final business judgment.',
      process: [
        ['01', 'Connect approved conversations', 'Define notice, purpose, access and retention, then connect selected recordings or communication sources.'],
        ['02', 'Extract sales signals', 'Identify needs, budget, stakeholders, timing, objections, competitors, commitments and unanswered questions.'],
        ['03', 'Create role-specific outputs', 'Give representatives summaries and actions, managers coaching evidence, and leaders traceable trend views.'],
        ['04', 'Return results to the workflow', 'Write reviewed structured outcomes into CRM, collaboration tools or the team’s current follow-up system.'],
      ],
      valueTitle: 'One call, three forms of business value',
      value: [
        ['Sales follow-up', 'Recover context quickly and clarify commitments, open questions and the focus of the next contact.'],
        ['Manager coaching', 'Review specific moments in discovery, listening, qualification and objection handling—not outcomes alone.'],
        ['Business insight', 'See recurring needs, loss reasons, competitor mentions and product feedback across conversations.'],
      ],
      fitTitle: 'Which calls are worth analyzing first?',
      fit: ['High-value calls contain substantial decision context', 'Long sales cycles require continuity across conversations', 'Managers spend too much time sampling calls', 'Recordings exist but structured customer records do not', 'The organization can establish lawful consent and data boundaries'],
      faqTitle: 'AI sales call analysis FAQ',
      faqs: [
        ['How is it different from call transcription?', 'Transcription captures what was said. TellWin structures customer state, objections, commitments, next actions and patterns around the sales workflow.'],
        ['Does it automatically score representatives?', 'It can surface evidence against criteria approved by the organization, but uncalibrated model scores should not replace manager judgment or become the sole performance measure.'],
        ['Can it connect to our CRM?', 'Start by validating fields, accuracy and usage, then define the write-back scope from available system interfaces. Replacing the CRM is not required.'],
        ['How is customer privacy handled?', 'A pilot should define notice and consent, purpose, access, retention and deletion. The final approach must reflect local law and company policy.'],
      ],
      proofNote: 'This page describes the target workflow and public TellWin capabilities. Conversation sources, accuracy, integrations and compliance must be confirmed through representative samples and implementation review.',
    },
    ar: {
      kicker: 'تحليل مكالمات المبيعات بالذكاء الاصطناعي',
      title: 'تجاوز نسخ مكالمات المبيعات\nلفهم سبب إقدام المشتري أو تردده.',
      intro: 'تنظّم TellWin مكالمات المبيعات والمحادثات المباشرة المصرح بها إلى احتياجات وإشارات شراء واعتراضات وذكر للمنافسين والتزامات وخطوات تالية، لتساعد البائع على المتابعة والمدير على التدريب من سياق حقيقي.',
      primaryAction: 'ناقش تجربة لتحليل المكالمات',
      secondaryAction: 'استكشف TellWin',
      problemsTitle: 'لماذا لا تنتج المكالمات المسجلة رؤى مبيعات كافية؟',
      problemsIntro: 'يضمن التسجيل الاحتفاظ بالمحادثة، لكنه لا يحدد من يراجعها وما المهم وما الإجراء التالي. لذلك يبقى سياق العميل خارج سير العمل عند الاعتماد على الذاكرة والعينات المحدودة.',
      problems: [
        ['لا يمكن إعادة الاستماع إلى كل مكالمة', 'لا يستطيع المدير سماع كل التسجيلات، وقد تفوّت العينات العشوائية محادثات تحتاج إلى متابعة أو تدريب عاجل.'],
        ['الملخص العام يفتقر إلى بنية المبيعات', 'قد لا يميز الملخص بين الميزانية وأصحاب القرار والتوقيت والاعتراضات والمنافسين والالتزامات.'],
        ['يبقى التحليل منفصلاً عن الإجراء', 'حتى الملخص المفيد يفقد قيمته إذا لم يصل إلى CRM والمهام ومراجعات المدير.'],
      ],
      processTitle: 'من مكالمة مبيعات إلى متابعة قابلة للتنفيذ',
      processIntro: 'تُضبط الحقول ومعايير التقييم وفق سير العمل الفعلي مع الاحتفاظ بالمصدر والمراجعة البشرية، فلا يحل مخرج النموذج محل الحكم المهني النهائي.',
      process: [
        ['01', 'ربط المحادثات المصرح بها', 'تحديد الإشعار والغرض والصلاحيات والاحتفاظ ثم ربط التسجيلات أو مصادر التواصل المختارة.'],
        ['02', 'استخراج إشارات المبيعات', 'تحديد الاحتياجات والميزانية والأطراف والتوقيت والاعتراضات والمنافسين والالتزامات والأسئلة المفتوحة.'],
        ['03', 'إنتاج نتائج حسب الدور', 'ملخصات وإجراءات للبائع وأدلة تدريب للمدير واتجاهات قابلة للتتبع للقيادة.'],
        ['04', 'إعادة النتائج إلى سير العمل', 'كتابة النتائج المنظمة بعد مراجعتها في CRM أو أدوات التعاون أو نظام المتابعة الحالي.'],
      ],
      valueTitle: 'مكالمة واحدة وثلاث قيم للأعمال',
      value: [
        ['متابعة المبيعات', 'استعادة السياق وتوضيح الالتزامات والأسئلة المفتوحة ومحور الاتصال التالي.'],
        ['تدريب المدير', 'مراجعة لحظات محددة في الاستكشاف والاستماع والتأهيل ومعالجة الاعتراضات بدلاً من النتائج فقط.'],
        ['رؤية الأعمال', 'اكتشاف الاحتياجات وأسباب الخسارة والمنافسين وملاحظات المنتج المتكررة عبر المحادثات.'],
      ],
      fitTitle: 'ما المكالمات الأنسب للبدء؟',
      fit: ['مكالمات عالية القيمة تضم سياقاً مهماً للقرار', 'دورات مبيعات طويلة تحتاج إلى استمرارية', 'ارتفاع تكلفة الاستماع اليدوي لدى المديرين', 'وجود تسجيلات من دون ملفات عملاء منظمة', 'إمكانية تأسيس موافقة قانونية وحدود واضحة للبيانات'],
      faqTitle: 'أسئلة شائعة حول تحليل مكالمات المبيعات',
      faqs: [
        ['ما الفرق بينه وبين النسخ النصي؟', 'يسجل النسخ ما قيل، بينما تنظّم TellWin حالة العميل والاعتراضات والالتزامات والخطوات التالية والأنماط وفق سير المبيعات.'],
        ['هل يقيّم البائعين تلقائياً؟', 'يمكنه إظهار أدلة وفق معايير تعتمدها المؤسسة، لكن لا ينبغي أن تستبدل الدرجات غير المعايرة حكم المدير أو تكون مقياس الأداء الوحيد.'],
        ['هل يمكن ربطه مع CRM؟', 'نبدأ بتقييم الحقول والدقة والاستخدام ثم نحدد نطاق الكتابة وفق واجهات النظام المتاحة، من دون ضرورة استبدال CRM.'],
        ['كيف تُحمى خصوصية العميل؟', 'يجب تحديد الإشعار والموافقة والغرض والصلاحيات والاحتفاظ والحذف، وأن يعكس التنفيذ القانون المحلي وسياسة المؤسسة.'],
      ],
      proofNote: 'تصف الصفحة سير العمل المستهدف وقدرات TellWin العامة. يجب تأكيد مصادر المحادثات والدقة والتكامل والامتثال بعينات ممثلة ومراجعة التنفيذ.',
    },
  },
  automotive: {
    zh: {
      kicker: 'AUTOMOTIVE SALES AI',
      title: '让每一次试驾与门店沟通，\n都成为下一步成交的客户依据。',
      intro: 'TellWin 面向汽车经销商和品牌销售团队，将获准采集的展厅、试驾与跟进沟通整理为车型偏好、预算、置换、配置关注、竞品比较、家庭决策和下一步，帮助顾问连续跟进，也帮助管理者看见真实客户声音。',
      primaryAction: '讨论汽车销售试点',
      secondaryAction: '了解销售对话智能',
      problemsTitle: '为什么试驾结束后，最重要的客户信息容易消失？',
      problemsIntro: '汽车购买同时包含产品、价格、金融、置换和家庭意见。只记录“意向车型”和“跟进状态”，不足以让下一次沟通真正接续客户的决策过程。',
      problems: [
        ['需求藏在长对话里', '配置、空间、续航、操控、交付和用车场景交织在一起，手工备注很难完整保留。'],
        ['“再考虑”没有被解释', '价格、竞品、家庭意见、置换估值或金融方案都可能是真实阻力，但系统里常只剩模糊状态。'],
        ['门店经验难以复制', '优秀顾问如何提问、介绍和处理异议很难被系统看见，新人辅导依赖个人经验。'],
      ],
      processTitle: '汽车销售客户情报的四个步骤',
      processIntro: '从一个门店或团队开始，选定合法合规的沟通入口与可衡量的跟进任务，再决定是否扩大范围。',
      process: [
        ['01', '采集获准的销售沟通', '明确客户告知与权限边界后，连接展厅接待、试驾复盘或后续电话等选定场景。'],
        ['02', '生成购车客户画像', '识别车型、配置、预算、金融、置换、使用场景、决策人、竞品、顾虑和计划时间。'],
        ['03', '辅助顾问继续跟进', '形成摘要、待办、未确认信息和下一次触达重点，减少重复询问与交接损失。'],
        ['04', '汇总门店与产品洞察', '跨对话观察客户关注、流失原因、竞品反馈和辅导主题，为管理复盘提供语境。'],
      ],
      valueTitle: '服务顾问、门店经理与品牌团队',
      value: [
        ['销售顾问', '快速回顾客户完整语境，让报价、邀约和后续沟通更连续。'],
        ['门店经理', '从真实接待片段定位辅导机会，而不只依赖销量和活动量。'],
        ['品牌与产品团队', '持续看见配置关注、竞品比较、价格反馈和真实使用场景。'],
      ],
      fitTitle: '哪些汽车销售团队适合先验证？',
      fit: ['试驾和门店沟通对成交影响大', '车型、配置、金融和置换信息复杂', '同一客户由多人或多渠道接续', '已有 CRM，但备注仍依赖顾问手工填写', '希望以真实接待样本验证准确性和采用情况'],
      faqTitle: '汽车销售 AI 常见问题',
      faqs: [
        ['TellWin 是汽车 CRM 吗？', '不是。TellWin 聚焦对话理解与客户情报，可把经确认的结构化结果接回现有 CRM 或门店系统。'],
        ['能识别车型和行业术语吗？', '可以围绕品牌、车型、配置和业务词汇建立评测与配置，但具体准确性需要用代表性真实样本验证。'],
        ['会自动联系客户吗？', '默认先为顾问生成摘要、待办和建议，由人员确认后执行；自动化范围取决于渠道、规则和合规边界。'],
        ['试点应该从哪里开始？', '选择一个门店、一个沟通场景和一组明确任务，对识别质量、跟进使用和管理价值进行真实评测。'],
      ],
      proofNote: '本页描述汽车销售目标场景与实施方法，不代表已与所有汽车品牌、门店系统或沟通渠道完成标准化接入，最终范围以试点评测为准。',
    },
    en: {
      kicker: 'AUTOMOTIVE SALES AI',
      title: 'Turn every test drive and showroom conversation\ninto evidence for the next sales action.',
      intro: 'TellWin helps automotive retailers and brand sales teams structure approved showroom, test-drive and follow-up conversations into model preferences, budget, trade-in, feature priorities, competitor comparisons, household decisions and next actions.',
      primaryAction: 'Discuss an automotive sales pilot',
      secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why does critical buyer context disappear after the test drive?',
      problemsIntro: 'A vehicle purchase combines product, pricing, finance, trade-in and household input. Recording only the preferred model and follow-up status cannot preserve the buyer’s full decision process.',
      problems: [
        ['Needs are buried in long conversations', 'Features, space, range, handling, delivery and driving scenarios overlap, making complete manual notes difficult.'],
        ['“Still considering” remains unexplained', 'Price, competitors, family input, trade-in valuation or finance may be the real barrier, while the system keeps only a vague status.'],
        ['Showroom expertise is hard to replicate', 'The discovery, explanation and objection handling of strong advisors remain difficult to observe and teach.'],
      ],
      processTitle: 'Four steps for automotive customer intelligence',
      processIntro: 'Start with one showroom or team, a compliant communication source and measurable follow-up tasks, then expand only after real evaluation.',
      process: [
        ['01', 'Capture approved sales conversations', 'With clear notice and permissions, connect selected showroom, test-drive review or follow-up call scenarios.'],
        ['02', 'Build the vehicle buyer profile', 'Identify model, features, budget, finance, trade-in, use case, decision roles, competitors, concerns and timing.'],
        ['03', 'Support advisor follow-up', 'Create summaries, actions, missing information and the focus for the next contact to reduce repetition and handoff loss.'],
        ['04', 'Aggregate showroom and product insight', 'Observe recurring interests, loss reasons, competitor feedback and coaching themes with traceable context.'],
      ],
      valueTitle: 'Value for advisors, showroom managers and brand teams',
      value: [
        ['Sales advisors', 'Recover the complete buyer context so quotations, appointments and follow-ups remain continuous.'],
        ['Showroom managers', 'Find coaching opportunities in real interactions instead of relying only on sales and activity counts.'],
        ['Brand and product teams', 'Continuously see feature priorities, competitor comparisons, price feedback and real use cases.'],
      ],
      fitTitle: 'Which automotive teams should validate first?',
      fit: ['Test drives and showroom conversations strongly influence decisions', 'Model, feature, finance and trade-in information is complex', 'Customers move between people or channels', 'CRM exists but notes still depend on manual entry', 'The team can evaluate accuracy and adoption with representative interactions'],
      faqTitle: 'Automotive sales AI FAQ',
      faqs: [
        ['Is TellWin an automotive CRM?', 'No. TellWin focuses on conversation understanding and customer intelligence, returning reviewed structured outcomes to an existing CRM or retail system.'],
        ['Can it recognize models and automotive terms?', 'Evaluation and configuration can cover brand, model, feature and workflow vocabulary, but accuracy must be validated with representative real samples.'],
        ['Will it contact customers automatically?', 'The default is to produce summaries, actions and suggestions for advisor review. Automation depends on channels, business rules and compliance.'],
        ['Where should a pilot begin?', 'Choose one showroom, one conversation scenario and clear tasks, then evaluate recognition quality, adoption and management value in real work.'],
      ],
      proofNote: 'This page describes the target automotive workflow and implementation approach. It does not claim standardized integration with every brand, retail system or communication channel; final scope depends on pilot evaluation.',
    },
    ar: {
      kicker: 'الذكاء الاصطناعي لمبيعات السيارات',
      title: 'حوّل كل تجربة قيادة ومحادثة في المعرض\nإلى أساس واضح للخطوة البيعية التالية.',
      intro: 'تساعد TellWin وكلاء السيارات وفرق مبيعات العلامات على تنظيم محادثات المعرض وتجربة القيادة والمتابعة المصرح بها إلى تفضيلات الطراز والميزانية والاستبدال والمواصفات والمنافسين وقرار الأسرة والخطوات التالية.',
      primaryAction: 'ناقش تجربة لمبيعات السيارات',
      secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا يختفي سياق المشتري المهم بعد تجربة القيادة؟',
      problemsIntro: 'يجمع شراء السيارة بين المنتج والسعر والتمويل والاستبدال ورأي الأسرة. ولا يكفي تسجيل الطراز المفضل وحالة المتابعة للاحتفاظ بمسار القرار كاملاً.',
      problems: [
        ['الاحتياجات مدفونة في حوار طويل', 'تتداخل المواصفات والمساحة والمدى والقيادة والتسليم والاستخدام، فيصعب تدوينها يدوياً بصورة كاملة.'],
        ['عبارة «ما زلت أفكر» بلا تفسير', 'قد يكون السعر أو المنافس أو الأسرة أو تقييم الاستبدال أو التمويل هو العائق الحقيقي، بينما يبقى في النظام وصف مبهم.'],
        ['يصعب نقل خبرة المعرض', 'تبقى طريقة أفضل المستشارين في الاستكشاف والشرح ومعالجة الاعتراضات صعبة الملاحظة والتعليم.'],
      ],
      processTitle: 'أربع خطوات لمعلومات عملاء السيارات',
      processIntro: 'ابدأ بمعرض أو فريق واحد ومصدر تواصل متوافق ومهام متابعة قابلة للقياس، ثم توسع بعد التقييم الفعلي فقط.',
      process: [
        ['01', 'جمع محادثات البيع المصرح بها', 'بعد توضيح الإشعار والصلاحيات، تُربط مواقف مختارة في المعرض أو تجربة القيادة أو مكالمات المتابعة.'],
        ['02', 'إنشاء ملف مشتري السيارة', 'تحديد الطراز والمواصفات والميزانية والتمويل والاستبدال والاستخدام والأطراف والمنافسين والمخاوف والتوقيت.'],
        ['03', 'دعم متابعة المستشار', 'إنتاج ملخصات ومهام ومعلومات ناقصة ومحور الاتصال التالي لتقليل التكرار وفقدان السياق.'],
        ['04', 'تجميع رؤى المعرض والمنتج', 'رصد الاهتمامات وأسباب الخسارة وملاحظات المنافسين وموضوعات التدريب المتكررة بسياق قابل للتتبع.'],
      ],
      valueTitle: 'قيمة للمستشار ومدير المعرض وفريق العلامة',
      value: [
        ['مستشارو المبيعات', 'استعادة سياق المشتري كاملاً لاستمرار العروض والمواعيد والمتابعة.'],
        ['مديرو المعارض', 'اكتشاف فرص التدريب من تفاعلات حقيقية بدلاً من أرقام المبيعات والنشاط فقط.'],
        ['فرق العلامة والمنتج', 'رؤية مستمرة لأولويات المواصفات والمنافسين والأسعار وحالات الاستخدام الفعلية.'],
      ],
      fitTitle: 'أي فرق سيارات أنسب للتقييم الأول؟',
      fit: ['تأثير تجربة القيادة وحوار المعرض في القرار', 'تعقيد معلومات الطراز والمواصفات والتمويل والاستبدال', 'انتقال العميل بين عدة أشخاص أو قنوات', 'وجود CRM مع اعتماد الملاحظات على الإدخال اليدوي', 'إمكانية تقييم الدقة والاستخدام بتفاعلات ممثلة'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات السيارات',
      faqs: [
        ['هل TellWin نظام CRM للسيارات؟', 'لا. تركز TellWin على فهم المحادثة ومعلومات العميل، وتعيد النتائج المنظمة بعد مراجعتها إلى CRM أو نظام التجزئة الحالي.'],
        ['هل يتعرف على الطرازات ومصطلحات السيارات؟', 'يمكن أن يغطي التقييم والإعداد العلامات والطرازات والمواصفات ومفردات العمل، لكن يجب تأكيد الدقة بعينات فعلية ممثلة.'],
        ['هل سيتواصل مع العميل تلقائياً؟', 'الوضع الافتراضي هو إنتاج ملخصات ومهام واقتراحات يراجعها المستشار، وتعتمد الأتمتة على القنوات والقواعد والامتثال.'],
        ['من أين تبدأ التجربة؟', 'اختر معرضاً وسيناريو محادثة ومهام واضحة، ثم قيّم جودة الاستخراج والاستخدام والقيمة الإدارية في العمل الفعلي.'],
      ],
      proofNote: 'تصف الصفحة سير العمل المستهدف لمبيعات السيارات ونهج التنفيذ، ولا تدّعي تكاملاً موحداً مع كل علامة أو نظام أو قناة. يعتمد النطاق النهائي على تقييم التجربة.',
    },
  },
  realEstate: {
    zh: {
      kicker: 'REAL ESTATE SALES AI',
      title: '让每一次房产顾问沟通，\n都沉淀为可跟进的客户情报。',
      intro: 'TellWin 面向迪拜及其他高价值房地产销售团队，将电话、面谈和私域沟通中的预算、区域偏好、户型需求、购买动机、决策人和下一步整理为统一客户上下文，帮助顾问跟进，也帮助管理者看见真实销售现场。',
      primaryAction: '讨论房地产销售试点',
      secondaryAction: '了解销售对话智能',
      problemsTitle: '房地产销售为什么容易丢失客户语境？',
      problemsIntro: '客户可能跨时区、跨语言、跨渠道比较多个项目。线索数量不等于有效跟进；决定转化质量的，往往是团队能否完整理解并接续每一次沟通。',
      problems: [
        ['客户需求分散在不同渠道', '电话、WhatsApp、面谈和 CRM 备注彼此割裂，顾问很难快速恢复完整上下文。'],
        ['管理者只看到结果和活动量', '通话次数和跟进状态无法说明顾问是否识别预算、决策角色、真实顾虑与购买时点。'],
        ['跨语言团队难以统一服务标准', '英文、阿语与其他语言沟通并存，客户表达和优秀顾问方法难以系统沉淀。'],
      ],
      processTitle: '为房地产销售设计的客户情报流程',
      processIntro: '先从一个团队、一个渠道和一组可衡量的跟进目标开始，不要求企业先替换 CRM。',
      process: [
        ['01', '采集获准的客户沟通', '连接选定的电话、面谈或私域入口，并明确当地法规、公司政策和客户告知要求。'],
        ['02', '生成房产客户档案', '识别预算、用途、自住或投资偏好、区域、户型、付款计划、决策人、顾虑和时间线。'],
        ['03', '辅助顾问及时跟进', '输出沟通摘要、待办、未回答问题和下一步建议，减少交接与重复询问。'],
        ['04', '让管理者看见共性', '发现反复出现的项目反馈、流失原因、团队辅导重点与市场问题。'],
      ],
      valueTitle: '从单次跟进到团队级增长能力',
      value: [
        ['经纪人和置业顾问', '快速恢复客户上下文，减少整理时间，让后续沟通更连续。'],
        ['销售经理', '基于真实沟通做辅导，识别线索质量、跟进缺口和团队共性。'],
        ['开发商与项目团队', '汇总客户对区域、户型、价格、付款方式和竞品项目的真实反馈。'],
      ],
      fitTitle: '适合哪些房地产团队？',
      fit: ['服务国际客户的迪拜经纪公司', '拥有多项目、多语言顾问团队的开发商', '高端住宅、投资物业与长周期客户', '已经使用 CRM，但沟通上下文仍依赖个人', '希望先以小范围真实数据验证 AI 销售能力'],
      faqTitle: '房地产销售 AI 常见问题',
      faqs: [
        ['TellWin 是房地产 CRM 吗？', '不是。TellWin 聚焦客户对话理解与销售情报，可与现有 CRM 配合，将更完整的沟通上下文写回客户记录。'],
        ['支持英文和阿语沟通吗？', '产品方向覆盖多语言沟通，但具体语言、口音与业务词汇需要在试点中用真实样本评测后确认。'],
        ['能否直接给客户发送回复？', '默认先生成摘要、待办和建议，由顾问确认后行动；是否自动发送取决于渠道能力、业务规则与合规边界。'],
        ['如何开始迪拜市场试点？', '选择一个销售团队、一类客户和一个沟通入口，明确数据与合规边界，再用真实跟进任务验证准确性和采用情况。'],
      ],
      proofNote: '迪拜房地产页面描述目标场景与实施方式，不代表已在所有语言、渠道或当地系统完成标准化接入。具体能力以试点评测和合规确认结果为准。',
    },
    en: {
      kicker: 'AI SALES COPILOT FOR DUBAI REAL ESTATE',
      title: 'Turn every property conversation\ninto customer intelligence your team can act on.',
      intro: 'TellWin helps high-value real estate sales teams in Dubai and similar markets structure budget, location preferences, property requirements, buyer motivation, decision roles and next actions from calls, meetings and private messaging—giving advisors continuity and managers a clearer view of real sales conversations.',
      primaryAction: 'Discuss a real estate pilot',
      secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why do real estate teams lose customer context?',
      problemsIntro: 'Buyers compare projects across time zones, languages and channels. Lead volume alone does not create effective follow-up; conversion quality depends on whether the team can understand and continue every important conversation.',
      problems: [
        ['Buyer needs are scattered across channels', 'Calls, WhatsApp, meetings and CRM notes remain disconnected, making full context difficult to recover.'],
        ['Managers see activity, not conversation quality', 'Call counts and statuses do not show whether an advisor understood budget, decision roles, concerns and purchase timing.'],
        ['Multilingual teams struggle to standardize service', 'English, Arabic and other languages coexist, while customer language and top-advisor methods remain difficult to retain.'],
      ],
      processTitle: 'A customer intelligence workflow for property sales',
      processIntro: 'Start with one team, one communication source and measurable follow-up goals. There is no requirement to replace the CRM first.',
      process: [
        ['01', 'Capture approved conversations', 'Connect selected calls, meetings or private channels with clear local legal, company policy and customer notice requirements.'],
        ['02', 'Build the property buyer profile', 'Identify budget, use case, investment or end-user intent, location, unit type, payment plan, decision roles, concerns and timing.'],
        ['03', 'Help advisors follow up', 'Produce summaries, actions, unanswered questions and next-step guidance to reduce handoff gaps and repeated questions.'],
        ['04', 'Show managers the patterns', 'Surface recurring project feedback, loss reasons, coaching priorities and market questions across conversations.'],
      ],
      valueTitle: 'From individual follow-up to a team growth capability',
      value: [
        ['Property advisors', 'Recover buyer context quickly, spend less time organizing notes and maintain continuity.'],
        ['Sales managers', 'Coach from real conversations and identify lead-quality, follow-up and team-wide gaps.'],
        ['Developers and project teams', 'Aggregate direct feedback about locations, units, pricing, payment plans and competing projects.'],
      ],
      fitTitle: 'Who is this designed for?',
      fit: ['Dubai brokerages serving international buyers', 'Developers with multilingual, multi-project sales teams', 'Luxury residential and investment-property sales', 'Teams with CRM but conversation context still owned by individuals', 'Organizations that want a focused real-data AI pilot first'],
      faqTitle: 'Dubai real estate sales AI FAQ',
      faqs: [
        ['Is TellWin a real estate CRM?', 'No. TellWin focuses on conversation understanding and sales intelligence, complementing the CRM by returning richer customer context to existing records.'],
        ['Does it support English and Arabic?', 'The product direction covers multilingual conversations, but each language, accent and property vocabulary must be evaluated with representative pilot samples.'],
        ['Can it automatically message buyers?', 'The default approach produces summaries, actions and suggestions for advisor review. Automation depends on channel capability, business rules and compliance boundaries.'],
        ['How would a Dubai pilot start?', 'Choose one sales team, buyer segment and communication source; define data and compliance boundaries; then evaluate accuracy and adoption using real follow-up work.'],
      ],
      proofNote: 'This page describes the target workflow and implementation approach. It does not claim standardized integration across every language, channel or local system. Final scope depends on pilot evaluation and compliance review.',
    },
    ar: {
      kicker: 'مساعد مبيعات ذكي لعقارات دبي',
      title: 'حوّل كل محادثة عقارية\nإلى معلومات عملاء يستطيع فريقك تنفيذها.',
      intro: 'تساعد TellWin فرق مبيعات العقارات عالية القيمة في دبي والأسواق المشابهة على تنظيم الميزانية والمناطق المفضلة ومتطلبات العقار ودافع الشراء وأصحاب القرار والخطوات التالية من المكالمات والاجتماعات والرسائل الخاصة، لتمنح المستشار استمرارية والمدير رؤية أوضح للمبيعات الفعلية.',
      primaryAction: 'ناقش تجربة لفريق عقاري',
      secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا تفقد فرق العقارات سياق العميل؟',
      problemsIntro: 'يقارن المشترون المشاريع عبر مناطق زمنية ولغات وقنوات متعددة. كثرة العملاء المحتملين لا تضمن المتابعة؛ فجودة التحويل تعتمد على قدرة الفريق على فهم كل محادثة مهمة ومواصلتها.',
      problems: [
        ['احتياجات المشتري موزعة بين القنوات', 'تبقى المكالمات وWhatsApp والاجتماعات وملاحظات CRM منفصلة، فيصعب استعادة السياق الكامل.'],
        ['يرى المدير النشاط ولا يرى جودة الحوار', 'لا توضح أعداد المكالمات والحالات ما إذا فهم المستشار الميزانية وأصحاب القرار والمخاوف وموعد الشراء.'],
        ['يصعب توحيد الخدمة في الفرق متعددة اللغات', 'تتعايش العربية والإنجليزية ولغات أخرى، بينما يصعب الاحتفاظ بلغة العملاء وأساليب أفضل المستشارين.'],
      ],
      processTitle: 'سير معلومات عملاء مصمم للمبيعات العقارية',
      processIntro: 'ابدأ بفريق واحد ومصدر تواصل واحد وأهداف متابعة قابلة للقياس، من دون اشتراط استبدال CRM أولاً.',
      process: [
        ['01', 'جمع المحادثات المصرح بها', 'ربط المكالمات أو الاجتماعات أو القنوات المختارة مع مراعاة القانون المحلي وسياسة الشركة وإشعار العميل.'],
        ['02', 'إنشاء ملف مشتري العقار', 'تحديد الميزانية والغرض والاستثمار أو السكن والمنطقة ونوع الوحدة وخطة الدفع وأصحاب القرار والمخاوف والتوقيت.'],
        ['03', 'مساعدة المستشار على المتابعة', 'إنتاج ملخصات ومهام وأسئلة غير مجابة واقتراح الخطوة التالية لتقليل فجوات التسليم وتكرار الأسئلة.'],
        ['04', 'إظهار الأنماط للإدارة', 'اكتشاف ملاحظات المشاريع وأسباب الخسارة وأولويات التدريب وأسئلة السوق المتكررة.'],
      ],
      valueTitle: 'من متابعة فردية إلى قدرة نمو للفريق',
      value: [
        ['المستشارون العقاريون', 'استعادة سياق المشتري بسرعة وتقليل وقت الملاحظات والحفاظ على استمرارية الحوار.'],
        ['مديرو المبيعات', 'التدريب من محادثات فعلية واكتشاف فجوات جودة العملاء والمتابعة والفريق.'],
        ['المطورون وفرق المشاريع', 'تجميع ملاحظات مباشرة حول المناطق والوحدات والأسعار وخطط الدفع والمشاريع المنافسة.'],
      ],
      fitTitle: 'لمن صُمم هذا الحل؟',
      fit: ['شركات الوساطة في دبي التي تخدم مشترين دوليين', 'المطورون ذوو فرق مبيعات متعددة المشاريع واللغات', 'مبيعات المساكن الفاخرة والعقارات الاستثمارية', 'فرق تستخدم CRM لكن سياق المحادثة ما زال لدى الأفراد', 'مؤسسات تريد تجربة ذكاء اصطناعي محددة ببيانات فعلية'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات عقارات دبي',
      faqs: [
        ['هل TellWin نظام CRM عقاري؟', 'لا. تركز TellWin على فهم المحادثة وذكاء المبيعات، وتكمل CRM بإعادة سياق أغنى إلى سجل العميل.'],
        ['هل يدعم العربية والإنجليزية؟', 'يشمل اتجاه المنتج المحادثات متعددة اللغات، لكن يجب تقييم كل لغة ولهجة ومفردات عقارية بعينات ممثلة في التجربة.'],
        ['هل يمكنه إرسال رسائل للمشترين تلقائياً؟', 'ينتج النهج الافتراضي ملخصات ومهام واقتراحات يراجعها المستشار. وتعتمد الأتمتة على القناة وقواعد العمل وحدود الامتثال.'],
        ['كيف تبدأ تجربة في دبي؟', 'اختر فريق مبيعات وشريحة مشترين ومصدر تواصل واحداً، وحدد حدود البيانات والامتثال، ثم قيّم الدقة والاستخدام بمهام متابعة فعلية.'],
      ],
      proofNote: 'تصف هذه الصفحة سير العمل المستهدف ونهج التنفيذ ولا تدّعي تكاملاً موحداً مع كل لغة أو قناة أو نظام محلي. يعتمد النطاق النهائي على تقييم التجربة ومراجعة الامتثال.',
    },
  },
}

export const seoLandingUi = {
  zh: {
    businessGap: '业务断点',
    conversationToAction: '从对话到行动',
    whoGetsValue: '价值角色',
    rightTeam: '从合适团队开始',
    related: '相关 TellWin 页面',
    tellwinLink: 'TellWin AI 销售副驾 →',
    fdeLink: 'FDE 企业 AI 落地服务 →',
    salesIntelligenceLink: '销售对话智能 →',
    realEstateLink: '房地产销售 AI →',
    salesCallLink: 'AI 销售通话分析 →',
    automotiveLink: '汽车销售 AI →',
    dubaiSource: '迪拜土地局市场资料 ↗',
  },
  en: {
    businessGap: 'THE BUSINESS GAP',
    conversationToAction: 'FROM CONVERSATION TO ACTION',
    whoGetsValue: 'WHO GETS VALUE',
    rightTeam: 'START WITH THE RIGHT TEAM',
    related: 'Related TellWin pages',
    tellwinLink: 'TellWin AI Sales Copilot →',
    fdeLink: 'FDE Enterprise AI Delivery →',
    salesIntelligenceLink: 'Sales Conversation Intelligence →',
    realEstateLink: 'Real Estate Sales AI →',
    salesCallLink: 'AI Sales Call Analysis →',
    automotiveLink: 'Automotive Sales AI →',
    dubaiSource: 'Dubai Land Department market reference ↗',
  },
  ar: {
    businessGap: 'فجوة العمل',
    conversationToAction: 'من المحادثة إلى الإجراء',
    whoGetsValue: 'من يستفيد',
    rightTeam: 'ابدأ بالفريق المناسب',
    related: 'صفحات TellWin ذات صلة',
    tellwinLink: 'مساعد مبيعات TellWin بالذكاء الاصطناعي ←',
    fdeLink: 'تنفيذ الذكاء الاصطناعي للمؤسسات FDE ←',
    salesIntelligenceLink: 'ذكاء محادثات المبيعات ←',
    realEstateLink: 'الذكاء الاصطناعي لمبيعات العقارات ←',
    salesCallLink: 'تحليل مكالمات المبيعات بالذكاء الاصطناعي ←',
    automotiveLink: 'الذكاء الاصطناعي لمبيعات السيارات ←',
    dubaiSource: 'مرجع سوق دائرة الأراضي والأملاك في دبي ↗',
  },
}
