export const seoLandingContent = {
  salesIntelligence: {
    zh: {
      kicker: 'SALES CONVERSATION INTELLIGENCE',
      title: '让销售对话不再散落，\n而是成为可行动的客户情报。',
      intro: 'TellWin 将面对面沟通、企业微信等渠道里的客户对话，整理为结构化客户档案、购买信号、异议、待办和跨团队洞察。它不是只做录音转写，而是让销售现场持续进入企业的跟进、辅导与经营决策。',
      primaryAction: '预约销售场景诊断',
      secondaryAction: '查看 TellWin 产品',
      problemsTitle: '为什么企业需要销售对话分析，而不只是 CRM？',
      problemsIntro: 'CRM 记录结果，客户对话解释结果。没有完整语境，管理者只能看到跟进状态，却很难知道客户为什么犹豫、销售哪里需要帮助、产品问题正在怎样重复出现。',
      problems: [
        ['客户信息依赖手工填写', '销售结束沟通后再补录，容易遗漏预算、决策人、竞品、真实异议和承诺事项。'],
        ['优秀经验留在少数人身上', '高绩效销售的提问、倾听和异议处理难以被团队看见，新人辅导只能依赖抽象复盘。'],
        ['客户原声到不了决策层', '一线需求经过多次转述，产品、市场和管理层看到的是结论，而不是可以核验的客户语境。'],
      ],
      processTitle: '从对话到行动的四个步骤',
      processIntro: '每一步都保留原始语境和人工确认边界，让 AI 提高整理与发现效率，不替代销售和管理者作最终判断。',
      process: [
        ['01', '连接沟通入口', '在获得授权并明确数据边界的前提下，接入面对面录音、企业微信或现有业务系统。'],
        ['02', '识别关键信息', '提取客户诉求、预算、角色、时间计划、购买信号、异议、竞品提及和跟进事项。'],
        ['03', '进入业务动作', '为销售生成摘要和下一步，为主管形成辅导线索，并把结构化结果写入 CRM 或飞书。'],
        ['04', '形成组织洞察', '跨对话观察需求、流失原因、话术表现和产品反馈，让客户原声进入经营复盘。'],
      ],
      valueTitle: '同一份客户情报，服务三个角色',
      value: [
        ['一线销售', '减少整理时间，快速回顾客户上下文、承诺与下一步。'],
        ['销售主管', '从真实对话定位团队共性问题，让辅导有具体依据。'],
        ['产品与市场', '持续看见客户需求、竞品比较和反复出现的反馈。'],
      ],
      fitTitle: '什么团队最适合先做试点？',
      fit: ['客单价高、成交依赖深度沟通', '销售周期长、多人参与决策', '客户资产容易随人员流动', '已有 CRM，但一线记录质量不稳定', '希望从真实数据开始验证 AI，而不是先换整套系统'],
      faqTitle: '销售对话智能常见问题',
      faqs: [
        ['它和录音转写工具有什么区别？', '转写解决“说了什么”，TellWin 进一步识别客户状态、业务信号、行动事项与跨对话趋势，并把结果接回销售流程。'],
        ['必须替换现有 CRM 吗？', '不需要。可以先从一个团队或一种沟通入口开始，将结果写回现有 CRM、飞书多维表格或其他业务系统。'],
        ['如何处理隐私与授权？', '试点前会明确采集告知、数据用途、权限、保存周期与脱敏要求；敏感行业可进一步讨论私有化和区域化部署。'],
        ['多久能判断是否值得继续？', '先选一个业务目标明确、数据可获得的小范围场景，用真实使用和评测结果决定是否扩展，不预设统一周期。'],
      ],
      proofNote: '页面描述为 TellWin 当前可公开的产品能力与实施方法。实际接入范围和效果取决于数据基础、合规要求与团队使用方式。',
    },
    en: {
      kicker: 'SALES CONVERSATION INTELLIGENCE',
      title: 'Turn scattered sales conversations\ninto actionable customer intelligence.',
      intro: 'TellWin structures customer conversations from in-person meetings, private messaging and existing business systems into customer records, buying signals, objections, follow-ups and cross-team insight. It goes beyond transcription so the reality of sales can inform execution, coaching and management decisions.',
      primaryAction: 'Book a sales workflow diagnosis',
      secondaryAction: 'Explore TellWin',
      problemsTitle: 'Why conversation intelligence—not CRM alone?',
      problemsIntro: 'CRM records outcomes; conversations explain them. Without the customer context, leaders can see pipeline status but not why a buyer hesitates, where a salesperson needs support or which product issue keeps recurring.',
      problems: [
        ['Critical context depends on manual entry', 'Post-call updates often miss budget, decision roles, competitors, real objections and commitments.'],
        ['Winning behavior stays with a few people', 'The questions, listening and objection handling of top performers remain hard to observe and difficult to teach.'],
        ['Customer voice never reaches decision-makers', 'After repeated retelling, product and marketing teams receive conclusions without the original, verifiable context.'],
      ],
      processTitle: 'Four steps from conversation to action',
      processIntro: 'Each step preserves source context and human review. AI accelerates organization and discovery; salespeople and leaders retain the final judgment.',
      process: [
        ['01', 'Connect communication sources', 'With clear consent and data boundaries, connect in-person recordings, private messaging or existing business systems.'],
        ['02', 'Identify business signals', 'Extract needs, budget, stakeholders, timing, buying signals, objections, competitor mentions and follow-up actions.'],
        ['03', 'Return insight to the workflow', 'Give salespeople summaries, managers coaching evidence, and write structured outcomes into CRM or collaboration tools.'],
        ['04', 'Build organizational intelligence', 'Analyze recurring needs, loss reasons, sales behavior and product feedback across conversations.'],
      ],
      valueTitle: 'One customer intelligence asset, three teams',
      value: [
        ['Sales representatives', 'Spend less time organizing notes and recover customer context, commitments and next actions quickly.'],
        ['Sales managers', 'Coach from real conversations and identify recurring team-level gaps.'],
        ['Product and marketing', 'Continuously see customer needs, competitor comparisons and repeated feedback.'],
      ],
      fitTitle: 'Which teams should pilot first?',
      fit: ['High-value purchases depend on consultative conversations', 'Long sales cycles involve several decision-makers', 'Customer relationships are vulnerable to staff turnover', 'A CRM exists, but frontline data quality is inconsistent', 'The team wants to validate AI with real data before replacing core systems'],
      faqTitle: 'Sales conversation intelligence FAQ',
      faqs: [
        ['How is this different from transcription?', 'Transcription captures what was said. TellWin identifies customer state, business signals, actions and cross-conversation patterns, then returns them to the sales workflow.'],
        ['Do we need to replace our CRM?', 'No. A pilot can start with one team or communication source and write structured results into the CRM or collaboration system you already use.'],
        ['How do you handle privacy and consent?', 'Before a pilot, we define notice and consent, purpose, access, retention and redaction. Private or regional deployment can be assessed for sensitive environments.'],
        ['How quickly can we evaluate a pilot?', 'Start with one measurable workflow and real data, then decide whether to expand from observed adoption and evaluation results rather than a fixed promise.'],
      ],
      proofNote: 'This page describes currently public TellWin capabilities and implementation methods. Integration scope and outcomes depend on data readiness, compliance requirements and team adoption.',
    },
    ar: {
      kicker: 'ذكاء محادثات المبيعات',
      title: 'حوّل محادثات المبيعات المتفرقة\nإلى معلومات عملاء قابلة للتنفيذ.',
      intro: 'تنظّم TellWin محادثات العملاء من اللقاءات المباشرة والرسائل الخاصة والأنظمة الحالية إلى ملفات عملاء وإشارات شراء واعتراضات ومهام متابعة ورؤى مشتركة. وهي تتجاوز النسخ النصي لتربط واقع المبيعات بالتنفيذ والتدريب والقرارات الإدارية.',
      primaryAction: 'احجز تشخيصاً لسير المبيعات',
      secondaryAction: 'استكشف TellWin',
      problemsTitle: 'لماذا تحتاج المؤسسة إلى ذكاء المحادثات إلى جانب CRM؟',
      problemsIntro: 'يسجل CRM النتائج، بينما تفسر المحادثات أسبابها. ومن دون سياق العميل يرى القادة حالة الفرص ولا يعرفون سبب التردد أو موضع حاجة البائع للدعم أو المشكلة المتكررة في المنتج.',
      problems: [
        ['السياق المهم يعتمد على الإدخال اليدوي', 'غالباً ما تفقد التحديثات اللاحقة الميزانية وأصحاب القرار والمنافسين والاعتراضات والالتزامات.'],
        ['خبرة الأداء العالي تبقى لدى أفراد محدودين', 'يصعب ملاحظة أسئلة أفضل البائعين وطريقة استماعهم ومعالجة الاعتراضات وتحويلها إلى تدريب للفريق.'],
        ['صوت العميل لا يصل إلى صانع القرار', 'بعد تكرار نقل المعلومات تصل إلى فرق المنتج والتسويق استنتاجات من دون السياق الأصلي القابل للتحقق.'],
      ],
      processTitle: 'أربع خطوات من المحادثة إلى الإجراء',
      processIntro: 'تحافظ كل خطوة على المصدر والمراجعة البشرية. يسرّع الذكاء الاصطناعي التنظيم والاكتشاف، بينما يبقى القرار النهائي لدى الفريق.',
      process: [
        ['01', 'ربط مصادر التواصل', 'بعد توضيح الموافقة وحدود البيانات، تُربط التسجيلات الميدانية والرسائل الخاصة أو أنظمة العمل الحالية.'],
        ['02', 'اكتشاف إشارات العمل', 'استخراج الاحتياجات والميزانية والأدوار والتوقيت وإشارات الشراء والاعتراضات والمنافسين وخطوات المتابعة.'],
        ['03', 'إعادة الرؤية إلى سير العمل', 'تقديم ملخصات للبائع وأدلة تدريب للمدير وكتابة النتائج المنظمة في CRM أو أدوات التعاون.'],
        ['04', 'بناء معرفة مؤسسية', 'تحليل الاحتياجات المتكررة وأسباب الخسارة وسلوك المبيعات وملاحظات المنتج عبر المحادثات.'],
      ],
      valueTitle: 'أصل واحد لمعلومات العملاء يخدم ثلاثة فرق',
      value: [
        ['فريق المبيعات', 'تقليل وقت تنظيم الملاحظات واستعادة سياق العميل والالتزامات والخطوة التالية بسرعة.'],
        ['مديرو المبيعات', 'التدريب انطلاقاً من محادثات فعلية واكتشاف الفجوات المشتركة في الفريق.'],
        ['المنتج والتسويق', 'رؤية مستمرة لاحتياجات العملاء ومقارنات المنافسين والملاحظات المتكررة.'],
      ],
      fitTitle: 'من الأنسب لبدء تجربة أولى؟',
      fit: ['عمليات شراء عالية القيمة تعتمد على الحوار الاستشاري', 'دورة مبيعات طويلة تضم عدة أصحاب قرار', 'علاقات العملاء معرضة للتأثر بتغير الموظفين', 'وجود CRM مع تفاوت جودة بيانات الخط الأمامي', 'الرغبة في اختبار الذكاء الاصطناعي ببيانات فعلية قبل استبدال الأنظمة الأساسية'],
      faqTitle: 'أسئلة شائعة حول ذكاء محادثات المبيعات',
      faqs: [
        ['ما الفرق بينه وبين النسخ النصي؟', 'النسخ يسجل ما قيل، بينما تحدد TellWin حالة العميل وإشارات العمل والإجراءات والأنماط عبر المحادثات ثم تعيدها إلى سير المبيعات.'],
        ['هل يجب استبدال CRM الحالي؟', 'لا. يمكن أن تبدأ التجربة بفريق أو مصدر تواصل واحد وكتابة النتائج المنظمة في النظام المستخدم حالياً.'],
        ['كيف تتعاملون مع الخصوصية والموافقة؟', 'قبل التجربة نحدد الإشعار والموافقة والغرض والصلاحيات ومدة الاحتفاظ وإخفاء البيانات، مع تقييم النشر الخاص أو الإقليمي عند الحاجة.'],
        ['متى يمكن تقييم التجربة؟', 'نبدأ بسير عمل قابل للقياس وبيانات فعلية، ثم نقرر التوسع بناءً على الاستخدام ونتائج التقييم بدلاً من وعد زمني ثابت.'],
      ],
      proofNote: 'تعرض هذه الصفحة قدرات TellWin وأساليب التنفيذ المتاحة للنشر حالياً. يعتمد نطاق الربط والنتائج على جاهزية البيانات ومتطلبات الامتثال وتبنّي الفريق.',
    },
  },
  realEstate: {
    zh: {
      kicker: 'REAL ESTATE SALES AI',
      title: '让每一次房产顾问沟通，\n都沉淀为可跟进的客户情报。',
      intro: 'TellWin 面向迪拜及其他高价值房地产销售团队，将电话、面谈和私域沟通中的预算、区域偏好、户型需求、购买动机、决策人和下一步整理为统一客户上下文，帮助顾问跟进，也帮助管理者看见真实销售现场。',
      primaryAction: '讨论房地产销售试点',
      secondaryAction: '了解销售对话智能',
      problemsTitle: '房地产销售为什么容易丢失客户语境？',
      problemsIntro: '客户可能跨时区、跨语言、跨渠道比较多个项目。线索数量不等于有效跟进；决定转化质量的，往往是团队能否完整理解并接续每一次沟通。',
      problems: [
        ['客户需求分散在不同渠道', '电话、WhatsApp、面谈和 CRM 备注彼此割裂，顾问很难快速恢复完整上下文。'],
        ['管理者只看到结果和活动量', '通话次数和跟进状态无法说明顾问是否识别预算、决策角色、真实顾虑与购买时点。'],
        ['跨语言团队难以统一服务标准', '英文、阿语与其他语言沟通并存，客户表达和优秀顾问方法难以系统沉淀。'],
      ],
      processTitle: '为房地产销售设计的客户情报流程',
      processIntro: '先从一个团队、一个渠道和一组可衡量的跟进目标开始，不要求企业先替换 CRM。',
      process: [
        ['01', '采集获准的客户沟通', '连接选定的电话、面谈或私域入口，并明确当地法规、公司政策和客户告知要求。'],
        ['02', '生成房产客户档案', '识别预算、用途、自住或投资偏好、区域、户型、付款计划、决策人、顾虑和时间线。'],
        ['03', '辅助顾问及时跟进', '输出沟通摘要、待办、未回答问题和下一步建议，减少交接与重复询问。'],
        ['04', '让管理者看见共性', '发现反复出现的项目反馈、流失原因、团队辅导重点与市场问题。'],
      ],
      valueTitle: '从单次跟进到团队级增长能力',
      value: [
        ['经纪人和置业顾问', '快速恢复客户上下文，减少整理时间，让后续沟通更连续。'],
        ['销售经理', '基于真实沟通做辅导，识别线索质量、跟进缺口和团队共性。'],
        ['开发商与项目团队', '汇总客户对区域、户型、价格、付款方式和竞品项目的真实反馈。'],
      ],
      fitTitle: '适合哪些房地产团队？',
      fit: ['服务国际客户的迪拜经纪公司', '拥有多项目、多语言顾问团队的开发商', '高端住宅、投资物业与长周期客户', '已经使用 CRM，但沟通上下文仍依赖个人', '希望先以小范围真实数据验证 AI 销售能力'],
      faqTitle: '房地产销售 AI 常见问题',
      faqs: [
        ['TellWin 是房地产 CRM 吗？', '不是。TellWin 聚焦客户对话理解与销售情报，可与现有 CRM 配合，将更完整的沟通上下文写回客户记录。'],
        ['支持英文和阿语沟通吗？', '产品方向覆盖多语言沟通，但具体语言、口音与业务词汇需要在试点中用真实样本评测后确认。'],
        ['能否直接给客户发送回复？', '默认先生成摘要、待办和建议，由顾问确认后行动；是否自动发送取决于渠道能力、业务规则与合规边界。'],
        ['如何开始迪拜市场试点？', '选择一个销售团队、一类客户和一个沟通入口，明确数据与合规边界，再用真实跟进任务验证准确性和采用情况。'],
      ],
      proofNote: '迪拜房地产页面描述目标场景与实施方式，不代表已在所有语言、渠道或当地系统完成标准化接入。具体能力以试点评测和合规确认结果为准。',
    },
    en: {
      kicker: 'AI SALES COPILOT FOR DUBAI REAL ESTATE',
      title: 'Turn every property conversation\ninto customer intelligence your team can act on.',
      intro: 'TellWin helps high-value real estate sales teams in Dubai and similar markets structure budget, location preferences, property requirements, buyer motivation, decision roles and next actions from calls, meetings and private messaging—giving advisors continuity and managers a clearer view of real sales conversations.',
      primaryAction: 'Discuss a real estate pilot',
      secondaryAction: 'Explore conversation intelligence',
      problemsTitle: 'Why do real estate teams lose customer context?',
      problemsIntro: 'Buyers compare projects across time zones, languages and channels. Lead volume alone does not create effective follow-up; conversion quality depends on whether the team can understand and continue every important conversation.',
      problems: [
        ['Buyer needs are scattered across channels', 'Calls, WhatsApp, meetings and CRM notes remain disconnected, making full context difficult to recover.'],
        ['Managers see activity, not conversation quality', 'Call counts and statuses do not show whether an advisor understood budget, decision roles, concerns and purchase timing.'],
        ['Multilingual teams struggle to standardize service', 'English, Arabic and other languages coexist, while customer language and top-advisor methods remain difficult to retain.'],
      ],
      processTitle: 'A customer intelligence workflow for property sales',
      processIntro: 'Start with one team, one communication source and measurable follow-up goals. There is no requirement to replace the CRM first.',
      process: [
        ['01', 'Capture approved conversations', 'Connect selected calls, meetings or private channels with clear local legal, company policy and customer notice requirements.'],
        ['02', 'Build the property buyer profile', 'Identify budget, use case, investment or end-user intent, location, unit type, payment plan, decision roles, concerns and timing.'],
        ['03', 'Help advisors follow up', 'Produce summaries, actions, unanswered questions and next-step guidance to reduce handoff gaps and repeated questions.'],
        ['04', 'Show managers the patterns', 'Surface recurring project feedback, loss reasons, coaching priorities and market questions across conversations.'],
      ],
      valueTitle: 'From individual follow-up to a team growth capability',
      value: [
        ['Property advisors', 'Recover buyer context quickly, spend less time organizing notes and maintain continuity.'],
        ['Sales managers', 'Coach from real conversations and identify lead-quality, follow-up and team-wide gaps.'],
        ['Developers and project teams', 'Aggregate direct feedback about locations, units, pricing, payment plans and competing projects.'],
      ],
      fitTitle: 'Who is this designed for?',
      fit: ['Dubai brokerages serving international buyers', 'Developers with multilingual, multi-project sales teams', 'Luxury residential and investment-property sales', 'Teams with CRM but conversation context still owned by individuals', 'Organizations that want a focused real-data AI pilot first'],
      faqTitle: 'Dubai real estate sales AI FAQ',
      faqs: [
        ['Is TellWin a real estate CRM?', 'No. TellWin focuses on conversation understanding and sales intelligence, complementing the CRM by returning richer customer context to existing records.'],
        ['Does it support English and Arabic?', 'The product direction covers multilingual conversations, but each language, accent and property vocabulary must be evaluated with representative pilot samples.'],
        ['Can it automatically message buyers?', 'The default approach produces summaries, actions and suggestions for advisor review. Automation depends on channel capability, business rules and compliance boundaries.'],
        ['How would a Dubai pilot start?', 'Choose one sales team, buyer segment and communication source; define data and compliance boundaries; then evaluate accuracy and adoption using real follow-up work.'],
      ],
      proofNote: 'This page describes the target workflow and implementation approach. It does not claim standardized integration across every language, channel or local system. Final scope depends on pilot evaluation and compliance review.',
    },
    ar: {
      kicker: 'مساعد مبيعات ذكي لعقارات دبي',
      title: 'حوّل كل محادثة عقارية\nإلى معلومات عملاء يستطيع فريقك تنفيذها.',
      intro: 'تساعد TellWin فرق مبيعات العقارات عالية القيمة في دبي والأسواق المشابهة على تنظيم الميزانية والمناطق المفضلة ومتطلبات العقار ودافع الشراء وأصحاب القرار والخطوات التالية من المكالمات والاجتماعات والرسائل الخاصة، لتمنح المستشار استمرارية والمدير رؤية أوضح للمبيعات الفعلية.',
      primaryAction: 'ناقش تجربة لفريق عقاري',
      secondaryAction: 'استكشف ذكاء المحادثات',
      problemsTitle: 'لماذا تفقد فرق العقارات سياق العميل؟',
      problemsIntro: 'يقارن المشترون المشاريع عبر مناطق زمنية ولغات وقنوات متعددة. كثرة العملاء المحتملين لا تضمن المتابعة؛ فجودة التحويل تعتمد على قدرة الفريق على فهم كل محادثة مهمة ومواصلتها.',
      problems: [
        ['احتياجات المشتري موزعة بين القنوات', 'تبقى المكالمات وWhatsApp والاجتماعات وملاحظات CRM منفصلة، فيصعب استعادة السياق الكامل.'],
        ['يرى المدير النشاط ولا يرى جودة الحوار', 'لا توضح أعداد المكالمات والحالات ما إذا فهم المستشار الميزانية وأصحاب القرار والمخاوف وموعد الشراء.'],
        ['يصعب توحيد الخدمة في الفرق متعددة اللغات', 'تتعايش العربية والإنجليزية ولغات أخرى، بينما يصعب الاحتفاظ بلغة العملاء وأساليب أفضل المستشارين.'],
      ],
      processTitle: 'سير معلومات عملاء مصمم للمبيعات العقارية',
      processIntro: 'ابدأ بفريق واحد ومصدر تواصل واحد وأهداف متابعة قابلة للقياس، من دون اشتراط استبدال CRM أولاً.',
      process: [
        ['01', 'جمع المحادثات المصرح بها', 'ربط المكالمات أو الاجتماعات أو القنوات المختارة مع مراعاة القانون المحلي وسياسة الشركة وإشعار العميل.'],
        ['02', 'إنشاء ملف مشتري العقار', 'تحديد الميزانية والغرض والاستثمار أو السكن والمنطقة ونوع الوحدة وخطة الدفع وأصحاب القرار والمخاوف والتوقيت.'],
        ['03', 'مساعدة المستشار على المتابعة', 'إنتاج ملخصات ومهام وأسئلة غير مجابة واقتراح الخطوة التالية لتقليل فجوات التسليم وتكرار الأسئلة.'],
        ['04', 'إظهار الأنماط للإدارة', 'اكتشاف ملاحظات المشاريع وأسباب الخسارة وأولويات التدريب وأسئلة السوق المتكررة.'],
      ],
      valueTitle: 'من متابعة فردية إلى قدرة نمو للفريق',
      value: [
        ['المستشارون العقاريون', 'استعادة سياق المشتري بسرعة وتقليل وقت الملاحظات والحفاظ على استمرارية الحوار.'],
        ['مديرو المبيعات', 'التدريب من محادثات فعلية واكتشاف فجوات جودة العملاء والمتابعة والفريق.'],
        ['المطورون وفرق المشاريع', 'تجميع ملاحظات مباشرة حول المناطق والوحدات والأسعار وخطط الدفع والمشاريع المنافسة.'],
      ],
      fitTitle: 'لمن صُمم هذا الحل؟',
      fit: ['شركات الوساطة في دبي التي تخدم مشترين دوليين', 'المطورون ذوو فرق مبيعات متعددة المشاريع واللغات', 'مبيعات المساكن الفاخرة والعقارات الاستثمارية', 'فرق تستخدم CRM لكن سياق المحادثة ما زال لدى الأفراد', 'مؤسسات تريد تجربة ذكاء اصطناعي محددة ببيانات فعلية'],
      faqTitle: 'أسئلة شائعة حول الذكاء الاصطناعي لمبيعات عقارات دبي',
      faqs: [
        ['هل TellWin نظام CRM عقاري؟', 'لا. تركز TellWin على فهم المحادثة وذكاء المبيعات، وتكمل CRM بإعادة سياق أغنى إلى سجل العميل.'],
        ['هل يدعم العربية والإنجليزية؟', 'يشمل اتجاه المنتج المحادثات متعددة اللغات، لكن يجب تقييم كل لغة ولهجة ومفردات عقارية بعينات ممثلة في التجربة.'],
        ['هل يمكنه إرسال رسائل للمشترين تلقائياً؟', 'ينتج النهج الافتراضي ملخصات ومهام واقتراحات يراجعها المستشار. وتعتمد الأتمتة على القناة وقواعد العمل وحدود الامتثال.'],
        ['كيف تبدأ تجربة في دبي؟', 'اختر فريق مبيعات وشريحة مشترين ومصدر تواصل واحداً، وحدد حدود البيانات والامتثال، ثم قيّم الدقة والاستخدام بمهام متابعة فعلية.'],
      ],
      proofNote: 'تصف هذه الصفحة سير العمل المستهدف ونهج التنفيذ ولا تدّعي تكاملاً موحداً مع كل لغة أو قناة أو نظام محلي. يعتمد النطاق النهائي على تقييم التجربة ومراجعة الامتثال.',
    },
  },
}

export const seoLandingUi = {
  zh: {
    businessGap: '业务断点',
    conversationToAction: '从对话到行动',
    whoGetsValue: '价值角色',
    rightTeam: '从合适团队开始',
    related: '相关 TellWin 页面',
    tellwinLink: 'TellWin AI 销售副驾 →',
    fdeLink: 'FDE 企业 AI 落地服务 →',
    realEstateLink: '房地产销售 AI →',
    dubaiSource: '迪拜土地局市场资料 ↗',
  },
  en: {
    businessGap: 'THE BUSINESS GAP',
    conversationToAction: 'FROM CONVERSATION TO ACTION',
    whoGetsValue: 'WHO GETS VALUE',
    rightTeam: 'START WITH THE RIGHT TEAM',
    related: 'Related TellWin pages',
    tellwinLink: 'TellWin AI Sales Copilot →',
    fdeLink: 'FDE Enterprise AI Delivery →',
    realEstateLink: 'Real Estate Sales AI →',
    dubaiSource: 'Dubai Land Department market reference ↗',
  },
  ar: {
    businessGap: 'فجوة العمل',
    conversationToAction: 'من المحادثة إلى الإجراء',
    whoGetsValue: 'من يستفيد',
    rightTeam: 'ابدأ بالفريق المناسب',
    related: 'صفحات TellWin ذات صلة',
    tellwinLink: 'مساعد مبيعات TellWin بالذكاء الاصطناعي ←',
    fdeLink: 'تنفيذ الذكاء الاصطناعي للمؤسسات FDE ←',
    realEstateLink: 'الذكاء الاصطناعي لمبيعات العقارات ←',
    dubaiSource: 'مرجع سوق دائرة الأراضي والأملاك في دبي ↗',
  },
}
